Siteimprove/alfa

packages/alfa-html/src/alphabet.ts
packages/alfa-html/test/alphabet.spec.ts

This implements RAWTEXT tokenisation.
Mind that this PR might conflict with #16, since the code is located at the same space in alphabet.ts.

Closes #15: Implement HTML RAWTEXT tokenisation steps

---

packages/alfa-dom/src/get-tab-sequence.ts
packages/alfa-dom/test/get-tab-sequence.spec.tsx

The `getTabSequence()` casts all elements to an TabIndexedElement, which contains its index weight. This is done, due to the fact that the order of which the elements are put into the array could return a bad order.

Closes #24: Implement `getTabSequence()`

---

packages/alfa-wcag/test/meta-refresh/rule.spec.tsx

Two test cases that increase the coverage of edge cases in the file to above 90%.

Adding some missing test-cases for the meta-refresh wcag rule

---

packages/alfa-aria/src/is-visible.ts
packages/alfa-aria/test/is-visible.spec.tsx
packages/alfa-dom/test/get-specificity.spec.ts
packages/alfa-dom/test/user-agent.spec.ts

This PR increases the coverage of various parts of the code-base, as well as fixing a bug, where aria-hidden wasn't inherited down to child elements.
I've implemented a check for this inheritance using a while-loop that climbs the tree of nodes instead of recursively calling isVisible. I chose this solution because isVisible does more than just checking for aria-hidden, which would cause an unnecessary performance penalty.

Increasing coverage and fixing a bug

---

scripts/helpers/metrics/arithmetic.js
scripts/helpers/metrics/logical.js
scripts/prepare.js

As discussed in person, precise heuristics to detect untested files are required. These heuristics must not create false positives.
This initial version extends the prepare method to look for source files without an associated test file. The unassociated files will then be compiled to search for exported functions.

Closes #49: Detect untested files

---

scripts/helpers/coverage.js

This changes the output of the coverage helper a bit:
- It will now print as many blocks as there is room for (not three), but minimum 1.
- ~It was sorting based on line number, which I removed (We don't know how many is going to be printed, so we can't slice it).~

Optmizing code output

---

packages/alfa-crypto/src/get-hash.ts
packages/alfa-crypto/src/types.ts
packages/alfa-crypto/test/get-hash.spec.ts

To get closer to our goal of 90% test-coverage, I have written tests to alfa-crypto. The task above introduced a lot of weirdness, so I have removed things from alfa-crypto, that does not work or have issues.
- I have removed the SHA1 and SHA512 algorithm target from alfa-crypto, as they are not shipped with SJCL (.. any more?).
- I have removed the UTF-8 codec as only some bit strings are valid UTF-8 sequences (see https://github.com/bitwiseshiftleft/sjcl/issues/131). I haven't gotten the UTF-8 codec to work on any string yet. If I have misunderstood something here, please correct me.

Tests and corrections in alfa-crypto

---

scripts/prepare.js

The current `prepare.js` does not work correctly on Windows, due to the incorrect path separator.

Incorrect path separator in build phase

---

packages/alfa-aria/test/features/html/a.spec.tsx
packages/alfa-aria/test/features/svg/a.spec.tsx

As my last act here at Siteimprove I quickly wanted to add these three tests regarding issue #132. This should be all the tests that are needed for now.

Closes #132: Added a few tests regarding the svg aria mappings

---

packages/alfa-rules/src/sia-r2/rule.ts
packages/alfa-rules/test/sia-r2/rule.spec.tsx

This pull request deals with the issue outlined in https://github.com/act-rules/act-rules.github.io/issues/446 by completely disregarding decorative images. From an implementation perspective, my suggested solution to that issue, namely changing the applicability to...
> any HTML <img> element that is either included in the accessibility tree or excluded from the accessibility tree because it is marked as decorative.
...seems to introduce too much complexity for too little gain. While we can easily determine if an image is decorative, tying its exclusion from the accessibility tree to the fact that it is decorative is not simple. The best solution to this would be to have the accessibility tree keep track of the reason why a given node was either excluded or included. If there's a strong …

Disregard decorative images in SIA-R2

---

scripts/common/tester.js

I keep switching between branches and having test failing because the `.js` is still here but orphaned from its `.ts(x)` (residing in another branch).
This will only run tests for files whose source is here, thus removing the need to manually cleaning when switching branches.

Test only files with corresponding .ts(x)

---

packages/alfa-rules/test/common/outcome.ts
packages/alfa-rules/test/sia-r1/rule.spec.tsx
packages/alfa-rules/test/sia-r2/rule.spec.tsx
packages/alfa-rules/test/sia-r24/rule.spec.tsx
packages/alfa-rules/test/sia-r38/rule.spec.tsx
packages/alfa-rules/test/sia-r57/rule.spec.tsx
packages/alfa-rules/test/sia-r64/rule.spec.tsx
packages/alfa-rules/test/sia-r68/rule.spec.tsx

Make the outcome test helpers accept expectation as an object (`{1: Outcomes.Foo}`) rather than an array of array (`[["1", Outcomes.Foo]]`).
Helpers argument is thus closer to how the expectations are defined in the rules.

Make outcome test helpers accept expectation object

---

packages/alfa-rules/src/common/predicate/is-document-element.ts
packages/alfa-rules/src/sia-r1/rule.ts
packages/alfa-rules/src/sia-r4/rule.ts
packages/alfa-rules/src/sia-r5/rule.ts
packages/alfa-rules/src/sia-r59/rule.ts
packages/alfa-rules/src/sia-r6/rule.ts

`isDocumentElement` was always used together with `isElement`. Refactoring these together.

Factor isElement in isDocumentElement

---

packages/alfa-cascade/src/selector-map.ts
packages/alfa-cypress/src/cypress.ts
packages/alfa-dom/src/style/sheet.ts
packages/alfa-puppeteer/src/puppeteer.ts
packages/alfa-webdriver/src/web-element.ts

Closes #219.
We need to coordinate this with @lukasbob as well as the crawler services that handle page rendering will need to include media conditions in their internal page representation if they don't already do so.

Include media conditions in `Sheet`

---

packages/alfa-highlight/src/index.ts
packages/alfa-highlight/src/marker.ts
packages/alfa-highlight/src/syntax.ts
packages/alfa-highlight/tsconfig.json

It struck me yesterday while looking into the different test integrations that the @siteimprove/alfa-highlight package is currently a little unfortunately organised. As it doesn't export any namespaces, the way it will typically be consumed within Alfa is like this:
```ts
import * as highlight from "@siteimprove/alfa-highlight";
highlight.highlight("html", "<div>Hello</div>");
highlight.mark.red("Foo");
```
Looking at the above, `highlight.highlight()` is not... great. I've therefore changed the name of the function to `syntax()` to better communicate what kind of highlighting is done, which leads to code like this:
```ts
highlight.syntax("html", "<div>Hello</div>");
```
Much better!

Reorganise @siteimprove/alfa-highlight

---

README.md
docs/examples/page-testing/puppeteer/package.json
packages/alfa-cli/bin/alfa/commands/audit.ts
packages/alfa-cli/bin/alfa/commands/scrape.ts
packages/alfa-cli/package.json
packages/alfa-cli/src/index.ts
packages/alfa-cli/src/oracle.ts
packages/alfa-cli/tsconfig.json
packages/alfa-device/src/viewport.ts
packages/alfa-puppeteer/package.json
packages/alfa-scraper/package.json
packages/alfa-scraper/src/awaiter.ts
packages/alfa-scraper/src/credentials.ts
packages/alfa-scraper/src/index.ts
packages/alfa-scraper/src/scraper.ts
packages/alfa-scraper/src/screenshot.ts
packages/alfa-scraper/tsconfig.json
packages/alfa-time/package.json
packages/alfa-time/src/index.ts
packages/alfa-time/src/time.ts
packages/alfa-time/src/timeout.ts
packages/alfa-time/test/time.spec.ts
packages/alfa-time/tsconfig.json
packages/tsconfig.json
yarn.lock

This pull request introduces a larger number of changes to the @siteimprove/alfa-scraper and @siteimprove/alfa-cli packages with the aim of better aligning the scraper implementation with the rest of Alfa and making available new features in the CLI for better managing page state. The pull request also introduces a new package, @siteimprove/alfa-time, for working with time and, in particular, timeouts.
A key change to the `Scraper` class is the introduction of the new `Awaiter` type, which models functions responsible for awaiting a given condition, such as document state or the presence of an element, signalling that a webpage is done loading:
https://github.com/Siteimprove/alfa/blob/1c3625e3adea6309ef2e0207ad01261b36299097/packages/alfa-scraper/src/awaiter.ts#L5-L8
Previously, the only …

Rework @siteimprove/alfa-scraper and @siteimprove/alfa-cli

---

packages/alfa-dom/src/node/fragment.ts

`Fragment` nodes never have parents but still allowed passing a parent during construction, which was an oversight. Passing a parent to `Fragment` nodes during construction was never intended to be allowed and I therefore consider it a bug that this was even possible.

Disallow `Fragment` nodes from having parents

---

packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/document.ts
packages/alfa-dom/src/node/element.ts

The `Element#content` property is currently used for modelling elements that allow embedded content, such as `<iframe>` and `<object>` elements. However, we did not have a property for modelling such a relation from the perspective of the embedded content itself, such as a `Document` node inside an `<iframe>` element. This pull request adds the `Document#frame` property for that purpose, modelled after [`Window.frameElement`](https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement).

Add `Document#frame` property to better model embedded documents

---

packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/attribute.ts
packages/alfa-dom/src/node/comment.ts
packages/alfa-dom/src/node/document.ts
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/shadow.ts
packages/alfa-dom/src/node/text.ts

This pull request makes it possible to pass traversal options to `Node#path()` in order to construct XPath expressions for the various traversal modes that `Node` provides. For example, given a document such as this...
```html
<div>
#shadow-root
<span>Hello world!</span>
</div>
```
...the `<span>` element would return the following XPath for `{ composed: true }`:
```
/div[1]/shadow-root()/span[1]
```
...and the following XPath for `{ flattened: true }`:
```
/div[1]/span[1]
```
The `shadow-root()` kind test is a non-standard feature introduced to deal with `Shadow` nodes and has not yet been implemented in `@siteimprove/alfa-xpath`.
For `<iframe>` elements such as this...
```html
<iframe>
#document
<html>
<body>
<span>Hello world</span>
</body>
</html>
```
...the `<span>` element would …

Allow passing traversal options to `Node#path()`

---

packages/alfa-scraper/src/scraper.ts

Previously, `Awaiter.ready` was used as the default in `Scraper#scrape()` which ran the risk of stylesheets not being available when the page was determined to be done loading. This pull request fixes that by changing the default to `Awaiter.loaded`.

Use `Awaiter.loaded` as the default in `Scraper#scrape()`

---

packages/alfa-scraper/src/awaiter.ts
packages/alfa-scraper/src/scraper.ts

This was an oversight from #226 as the `Timeout` class was introduced _after_ the `Awaiter` class.

Use `Timeout` and not `number` for timeouts in `Awaiter`

---

packages/alfa-cli/bin/alfa/commands/scrape.ts
packages/alfa-device/package.json
packages/alfa-device/src/device.ts
packages/alfa-device/src/index.ts
packages/alfa-device/src/preference.ts
packages/alfa-device/src/scripting.ts
packages/alfa-device/tsconfig.json
packages/alfa-hash/src/hash.ts
packages/alfa-scraper/src/scraper.ts

In working on #251, I realised that we're currently lacking scripting as a device parameter. This is needed to correctly handle rendering hints for the `<noscript>` element as they depend on whether scripting is enabled or not. This pull request therefore adds scripting as a device parameter and also adds user preferences as these are something we'll be needing.
The changes introduced are breaking as they add two additional required properties to the `Device.JSON` type. The `javascript` option for the `Scraper#scrape()` method has also been removed as the `Device#scripting` property now fulfils this need, and likewise has the `--[no-]javascript` flag in the CLI been renamed `--[no-]scripting` to align things.

Add scripting and user preferences as `Device` parameters

---

packages/alfa-highlight/package.json
packages/alfa-highlight/src/syntax.ts
packages/alfa-highlight/types/emphasize.d.ts

During my profiling of initialisation times, I discovered that eagerly loading syntax definitions for the 185-ish languages supported by highlight.js isn't particularly fast as it takes ~100 ms. This pull request fixes that by only loading syntax definitions as they're needed. The changes are breaking as the `syntax()` function now returns a promise.

Lazy load syntax definitions

---

packages/alfa-act/src/interview.ts
packages/alfa-act/src/rule.ts
packages/alfa-rules/src/common/applicability/audio.ts
packages/alfa-rules/src/common/applicability/video.ts
packages/alfa-rules/src/sia-r23/rule.ts
packages/alfa-rules/src/sia-r39/rule.ts
packages/alfa-rules/src/sia-r82/rule.ts

This pull request fixes a compiler crash in TypeScript 3.9 due to the recursive construction of the `Interview` type. This is fixed by limiting the depth of the recursion.
See https://github.com/microsoft/TypeScript/issues/38825.
Before:
https://github.com/Siteimprove/alfa/blob/f77af337f1ea1bc0ef5d100fbd2a06d34d2f32ef/packages/alfa-act/src/interview.ts#L8-L10
After:
https://github.com/Siteimprove/alfa/blob/907a9be4fb50c95307e1352a15fa9c22bfef8d79/packages/alfa-act/src/interview.ts#L16-L27

Prevent infinite instantiation of `Interview` type

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/node.ts
packages/alfa-aria/src/role.ts

On an `<img alt="" aria-label="foo" />`, Presentational role conflict resolution triggered but returns `none` again as it is the implicit role with `alt=""`.
This should fix it.
Role aspect can now take optional arguments.

Account for presentational role conflict resolution in ARIA feature mappings

---

packages/alfa-rules/src/common/applicability/video.ts

The `kind` attribute is actually enumerated 🤷 
https://html.spec.whatwg.org/multipage/media.html#attr-track-kind

Treat kind attribute as enumerated

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/node.ts
packages/alfa-aria/src/role.ts

We've built ourselves a nice footgun by putting the conflict resolution in `Node.build` which is bypassed by many functions such as `hasRole` calling `Role.from` directly…
Moving the resolution deeper to where role computation actually happens clean that up. And also avoids `Node.build` doing a double roundtrip to `Role.from`.
Also removing the default value of `isAllowedPresentational` from the individual features to eliminate the risk of them disagreeing on that…

Move presentational role conflict resolution down to Role.from

---

packages/alfa-cascade/src/rule-tree.ts
packages/alfa-cascade/src/selector-map.ts

The rule tree would inadvertently discard rules if their selector matched one already in the tree. I'm fearing this _might_ be a case of me running into a [Chesterton's fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) that I put up myself so a little more digging may be a good idea 🙈

Avoid discarding rules when adding to `RuleTree`

---

packages/alfa-style/src/property.ts
packages/alfa-style/src/property/background.ts
packages/alfa-style/src/style.ts

Add initial support for `background` shorthand property

---

packages/alfa-future/src/future.ts
packages/alfa-future/test/future.spec.ts

This pull requests implements the functionality that originally sparked the implementation of the current `Future<T>` type: The ability to synchronously resolve non-deferred futures. This is needed for the upcoming redesign of the `@siteimprove/alfa-assert` package tracked by #270.

Add `Future#get()` and accept thunked promises in `Future.from()`

---

packages/alfa-cli/bin/alfa/command/audit/run.ts
packages/alfa-formatter/package.json
packages/alfa-formatter/src/formatter.ts

These will still compile to CJS per our TypeScript configuration but will remove the dependency on Node.js and allow us to compile to native modules in the future. This change is breaking as it turns loading of formatters into an async operation.

Use dynamic import rather than `require()` for loading formatters

---

packages/alfa-aria/test/get-name.spec.tsx
packages/alfa-dom/h.ts
packages/alfa-dom/package.json
packages/alfa-dom/src/h.ts
packages/alfa-dom/src/index.ts
packages/alfa-dom/src/jsx.ts
packages/alfa-dom/tsconfig.json
packages/alfa-rules/test/sia-r45/rule.spec.tsx
packages/alfa-rules/test/sia-r69/rule.spec.tsx
packages/alfa-rules/test/sia-r71/rule.spec.tsx
packages/alfa-rules/test/sia-r72/rule.spec.tsx
packages/alfa-rules/test/sia-r73/rule.spec.tsx
packages/alfa-rules/test/sia-r74/rule.spec.tsx
packages/alfa-rules/test/sia-r75/rule.spec.tsx
packages/alfa-rules/test/sia-r80/rule.spec.tsx
packages/alfa-rules/test/sia-r83/rule.spec.tsx
packages/alfa-rules/test/sia-r84/rule.spec.tsx
packages/alfa-rules/test/sia-r85/rule.spec.tsx
packages/alfa-table/test/testcases.tsx

This pull request introduces a [HyperScript](https://github.com/hyperhype/hyperscript)-like DSL of sorts for constructing DOM. It's been in the cards for some time now that we've needed a better approach to constructing DOM, in particular for test cases, as code like the following has become very common practice:
https://github.com/Siteimprove/alfa/blob/a2a909ea04a84615e37cd41dd4c6d9b9de913a47/packages/alfa-rules/test/sia-r1/rule.spec.tsx#L13-L22
The new `h()` function and the associated `h` namespace help alleviate this by allowing code that instead looks like this:
```ts
const document = Document.fromDocument(
h.document([
h("html", {}, [
h("head", {}, [
h("title", {}, ["Hello world"]),
])
])
])
);
```
This can of course be mixed with JSX as well for an even nicer look:
```tsx
const …
```

Introduce HyperScript-like DSL for constructing DOM

---

packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx
packages/alfa-style/tsconfig.json

Closes #240 and depends on #281.

Correctly resolve important and overridden CSS properties

---

README.md
packages/alfa-act/src/audit.ts
packages/alfa-act/src/rule.ts
packages/alfa-assert/src/assert.ts
packages/alfa-cli/bin/alfa/command/audit/run.ts
packages/alfa-rules/src/index.ts

With most of the variance issues surrounding rules sorted out, I no longer see a reason to pass rules to the `Audit` class _after_ its construction. In fact, this has caused other issues due to the lack of type inference meaning that callers have had to explicitly annotate the target (`T`) and question (`Q`) type parameters as only the input (`I`) type would be inferred:
```ts
const rules: Array<Rule<Input, Type, Question>>;
let audit = Audit.of<Input, Type, Question>(input);
for (const rule of rules) {
audit = audit.add(rule);
}
```
This pull request solves that by requiring that rules be passed _during_ construction of the `Audit` class:
```ts
const rules: Array<Rule<Input, Type, Question>>;
const audit = Audit.of(input, rules);
```
This pull request also makes it possible to easily add …

Pass rules during construction of `Audit` class rather than after

---

packages/alfa-scraper/package.json
packages/alfa-scraper/src/scraper.ts
packages/alfa-scraper/test/fixture/internal-link.html
packages/alfa-scraper/test/fixture/location-change-delayed.html
packages/alfa-scraper/test/fixture/location-change-immediate.html
packages/alfa-scraper/test/fixture/meta-refresh-delayed.html
packages/alfa-scraper/test/fixture/meta-refresh-immediate.html
packages/alfa-scraper/test/scraper.spec.ts
packages/alfa-scraper/tsconfig.json

Previously, scraping a page whose URL contained a hash fragment (`https://example.com/#foo`) would fail for reasons that are still not entirely clear. The internals of the `#scrape()` has grown fairly complicated to deal with immediate client side redirects; this has been simplified and requests are now simply retried with the new URL upon encountering a redirect.

Refactor `Scraper#scrape()` internals to fix scraping of URLs with hash fragment

---

packages/alfa-css/src/syntax.ts
packages/alfa-dom/src/h.ts
packages/alfa-either/src/either.ts
packages/alfa-parser/src/parser.ts
packages/alfa-style/package.json
packages/alfa-style/src/property.ts
packages/alfa-style/src/property/overflow.ts
packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx
packages/alfa-style/tsconfig.json

I had a head full of ideas and an evening to spare so I went ahead with an implementation of custom properties. The implementation exposes no additional public API surface and so everything is dealt with transparently behind the scenes. The majority of the code introduced is additional test cases to exercise the many corners of the specification.
I also snuck in a variadic version of `Parser.either()` that should satisfy part of #292.
Closes #293.

Implement support for CSS Custom Properties

---

packages/alfa-css/src/syntax.ts
packages/alfa-css/src/syntax/block.ts
packages/alfa-css/src/syntax/component.ts
packages/alfa-css/src/syntax/declaration.ts
packages/alfa-css/src/syntax/function.ts
packages/alfa-css/src/syntax/token.ts
packages/alfa-css/test/syntax/declaration.spec.ts
packages/alfa-css/tsconfig.json
packages/alfa-style/package.json
packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx
packages/alfa-style/tsconfig.json

This pull request first and foremost fixes two issues in our handling of custom properties:
- Guaranteed-invalid values, including the `initial` keyword.
- `!important` custom properties.
It also fixes a bug in parsing CSS component values when blocks are involved. Namely, the ending token of blocks (`)`, `]`, or `}`) was not included in the final component value.

Fix several CSS component syntax and custom property issues

---

packages/alfa-rules/src/sia-r68/rule.ts
packages/alfa-rules/test/sia-r68/rule.spec.tsx

See https://github.com/act-rules/act-rules.github.io/issues/1426. I consider this to be a bug in the rule, hence the patch label.

Relax child requirement of R68 to at least one, not all

---

packages/alfa-aria/src/name.ts

Just what it says on the tin ☝️

Cache accessible names of `Text` nodes

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/src/node.ts
packages/alfa-aria/src/role.ts
packages/alfa-aria/test/node.spec.tsx
packages/alfa-rules/src/common/predicate/is-ignored.ts
packages/alfa-rules/src/common/predicate/is-perceivable.ts
packages/alfa-rules/test/sia-r21/rule.spec.tsx
packages/alfa-rules/test/sia-r82/rule.spec.tsx

This pull request improves the construction performance of ARIA `Node` instances by introducing the following changes:
- When computing names for form controls with connected `<label>` elements, the list of `<label>` element is re-used, rather than re-computed, for each document scope.
- The `State` interface used for encoding the name computation state is now a class whose methods attempt to re-use the current `State` instance whenever possible to reduce allocations and pressure on the garbage collector.
- The attributes supported by `Role` instances are now computed and stored on construction.
- Elements without ARIA attributes and roles are now included as `Container` instances, hence skipping an expensive name computation as these elements shouldn't be included in the accessibility …

Improve ARIA `Node` construction performance

---

packages/alfa-aria/src/node.ts
packages/alfa-aria/test/node.spec.tsx
packages/alfa-rules/test/sia-r13/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Nodes that have a tab index but no role or ARIA attribute were not exposed in the accessibility tree.  Now they are.
This notably excluded `<iframe>` from the accessibility tree, thus making most of them inapplicable for their relevant rules…

Expose elements in accessibility tree if they have a tab index

---

packages/alfa-rules/src/sia-r46/rule.ts
packages/alfa-rules/test/sia-r46/rule.spec.tsx

Ignore tables and headers that are presentational, even if they have non-presentational children.
Closes #390.

Ignore header cells of presentational tables in SIA-R46

---

packages/alfa-rules/src/sia-r14/rule.ts

This pull request adjusts the applicability of SIA-R14 in the following ways:
- The rule now only applies to focusable elements with a role that inherits from `widget`.
- The rule now only applies to elements with an `aria-label` or `aria-labelledby` attribute.

Adjust applicability of SIA-R14

---

packages/alfa-rules/src/sia-r68/rule.ts
packages/alfa-rules/test/sia-r68/rule.spec.tsx

SIA-R68: Exclude elements with an `aria-busy=true` ancestor

---

docs/examples/custom-testing/crawling/test.ts
docs/examples/custom-testing/scraping/test.ts
packages/alfa-cli/bin/alfa/command/scrape/run.ts
packages/alfa-cli/package.json
packages/alfa-cli/tsconfig.json
packages/alfa-crawler/package.json
packages/alfa-crawler/src/crawler.ts
packages/alfa-crawler/test/crawler.spec.ts
packages/alfa-crawler/tsconfig.json
packages/alfa-frontier/package.json
packages/alfa-frontier/src/frontier.ts
packages/alfa-frontier/test/frontier.spec.ts
packages/alfa-http/package.json
packages/alfa-http/src/request.ts
packages/alfa-http/src/response.ts
packages/alfa-http/tsconfig.json
packages/alfa-json-ld/package.json
packages/alfa-json-ld/src/expand.ts
packages/alfa-json-ld/tsconfig.json
packages/alfa-scraper/src/scraper.ts
packages/alfa-scraper/test/scraper.spec.ts
packages/alfa-scraper/tsconfig.json
packages/alfa-url/package.json
packages/alfa-url/src/index.ts
packages/alfa-url/src/url.ts
packages/alfa-url/src/url/builtin.ts
packages/alfa-url/test/url.spec.ts
packages/alfa-url/tsconfig.json
packages/alfa-web/src/page.ts
packages/tsconfig.json

This pull request introduces a new `@siteimprove/alfa-url` package with an implementation of an immutable URL class modelled on the WHATWG URL specification. An obvious question might be "why not just use the WHATWG URL DOM API?" to which the obvious answer is "well, it kinda does". That is, `URL.parse()` relies on the WHATWG URL DOM API for parsing URL strings and extracting URL records. From there, the `URL` class also adds some convenience like implementations of `Equatable`, `Hashable`, and `Serializable`, making it easy to use `URL` instances in the various data structures Alfa provides.
The caveat to this approach is of course that we now rely on the WHATWG URL specification being implemented by whatever runtime Alfa is used in, which shouldn't really be a problem. It's of course …

Introduce `@siteimprove/alfa-url` package

---

packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

This pull request implements step 2H of the accessible name computation with an important optimisation: Selective caching of names to avoid degenerating to quadratic complexity as seen prior to #360. The caching takes an "innocent until proven otherwise" approach in that the cache is consulted in the general case and selectively ignored in special cases. The only current case in which the cache is ignored is for name computations involving `aria-labelledby` references as these are not allowed to chain.
Closes #429.

Implement step 2H of the accessible name computation

---

packages/alfa-graph/package.json
packages/alfa-graph/src/graph.ts
packages/alfa-graph/test/graph.spec.ts
packages/alfa-graph/tsconfig.json

This pull request implements a traversal API for the `Graph` class, which is needed for correctly dealing with cyclic `aria-owns` references:
https://github.com/Siteimprove/alfa/blob/2db1ec794a867b858a8f971e48229332d5a8dd46/packages/alfa-aria/test/node.spec.tsx#L182-L188
The changes are breaking as `Graph#neighbors()` now returns `Iterable<T>` rather than `Option<Set<T>>`, which seemed like a strong promise.

Implement traversal API for `Graph`

---

packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/element/predicate.ts
packages/alfa-dom/src/node/element/predicate/is-browsing-context-container.ts
packages/alfa-dom/src/node/element/predicate/is-disabled.ts
packages/alfa-dom/src/node/element/predicate/is-draggable.ts
packages/alfa-dom/src/node/element/predicate/is-editing-host.ts
packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
packages/alfa-dom/test/node/element.spec.tsx
packages/alfa-dom/tsconfig.json
packages/alfa-rules/test/sia-r2/rule.spec.tsx

Fix several `Element#tabIndex()` cases

---

packages/alfa-cascade/package.json
packages/alfa-cascade/src/cascade.ts
packages/alfa-cascade/src/rule-tree.ts
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/tsconfig.json
packages/alfa-selector/package.json
packages/alfa-selector/src/context.ts
packages/alfa-selector/src/index.ts
packages/alfa-selector/src/selector.ts
packages/alfa-selector/test/selector.spec.tsx
packages/alfa-selector/tsconfig.json
packages/alfa-style/package.json
packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx
packages/alfa-style/tsconfig.json

This pull request implements style resolution for the following stateful pseudo classes:
- `:hover`
- `:active`
- `:focus`
- `:focus-within`
- `:focus-visible`
- `:link`
- `:visited`
A new class, `Context`, has been introduced to model context-dependant information during selector matching, such as which element is currently in focus, which elements have been visited, and so on. This class is heavily inspired by Servo ([`components/selectors/context.rs`][components/selectors/context.rs]) and works by modelling state as bit flags associated with elements. As an example, this means that it's up to the caller, not `Selector#matches()`, to decide if a given element links to a resource that has been visited; `Selector#matches()` simply checks the associated state, not the actual URL of the …

Implement style resolution for stateful pseudo classes

---

packages/alfa-rules/src/sia-r10/rule.ts
packages/alfa-rules/test/sia-r10/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Ignore elements not on the value of the `aria-disabled` attribute, but on the value of the `aria-disabled` state in the accessibility tree.
And reorder a bit the tests, to put the more generic (namespace), selective (element) and light at the start and only build the accessible node if needed.
Closes #516.

SIA-R10: ignore disabled elements

---

packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Closes #515.
Quick fix with a single used value, maybe not perfectly accurate.
I suggest we go with it for now and refine the code if this proves to be problematic.

SIA R83: assume a used value for `normal` line-height

---

packages/alfa-rules/src/sia-r53/rule.ts
packages/alfa-rules/test/sia-r53/rule.spec.tsx

SIA R53: ignore headings that are not in the accessibility tree

---

packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx

Properties that are explicitly declared as `initial` were still recorded with no source. Among other, this causes Alfa to loose the `!important` flag in declarations like `<div style="foo: initial !important">` and therefore to incorrectly pass https://act-rules.github.io/rules/78fd32#failed-example-6
Testing on 
```html
<html lang="en">
<style>
p { background-color: initial !important;}
</style>
<body>
<p>White</p>
<p style="background-color: blue;">Still white</p>
</body>
</html>
```
shows that the important flag on an explicit `initial` property is indeed respected.

Keep source of explicit `initial` properties

---

packages/alfa-act/src/outcome.ts
packages/alfa-array/src/array.ts
packages/alfa-branched/src/branched.ts
packages/alfa-collection/src/collection.ts
packages/alfa-either/src/either.ts
packages/alfa-either/src/left.ts
packages/alfa-either/src/right.ts
packages/alfa-iterable/src/iterable.ts
packages/alfa-json/src/serializable.ts
packages/alfa-lazy/src/lazy.ts
packages/alfa-list/src/list.ts
packages/alfa-map/src/map.ts
packages/alfa-option/src/option.ts
packages/alfa-option/src/some.ts
packages/alfa-record/src/record.ts
packages/alfa-result/src/err.ts
packages/alfa-result/src/ok.ts
packages/alfa-result/src/result.ts
packages/alfa-sequence/src/cons.ts
packages/alfa-sequence/src/nil.ts
packages/alfa-sequence/src/sequence.ts
packages/alfa-set/src/set.ts
packages/alfa-slice/src/slice.ts
packages/alfa-table/src/table.ts

This pull request makes the `#toJSON()` methods parametric for all container types to allow strongly typed JSON serialisation when working with these. The most common use case of this is by far when writing unit tests as these often do deep comparisons of JSON serialised structures. Consider, for example, a list of optional numbers:
```ts
const list: List<Option<number>>
```
Previously, when serialising this structure to JSON, you'd get the following type:
```ts
const json: List.JSON = list.toJSON()
```
Not... terribly helpful. It even becomes harmful when refactoring as TypeScript has no knowledge of the `Option.JSON` types nested within the serialised list structure. Had we typed out the structure by hand, as we often do when doing deep comparisons, TypeScript would not have applied the …

Make `#toJSON()` parametric for all container types

---

packages/alfa-rules/src/sia-r14/rule.ts
packages/alfa-rules/test/sia-r14/rule.spec.tsx
packages/alfa-rules/tsconfig.json

This pull request changes the expectation of SIA-R14 to assume that non-essential text, such as purely presentational text, has been made imperceivable. As such, imperceivable text is no longer required to be included in the accessible name of widget elements that receive their name from their contents.

Make SIA-R14 assume that non-essential text is imperceivable

---

packages/alfa-performance/package.json
packages/alfa-performance/src/index.ts
packages/alfa-performance/src/now.ts
packages/alfa-performance/src/performance.ts
packages/alfa-performance/tsconfig.json
packages/tsconfig.json

This pull request introduces a new package, @siteimprove/alfa-performance, for working with performance measurements. Its design is based on the [User Timing](https://www.w3.org/TR/user-timing/) API, but is implemented independently of runtime environment (browsers vs. Node.js) and aims to solve some of the shortcomings of the User Timing API:
- **Lack of memory bounds**: With the User Timing API, performance entries are added to and kept in an internal buffer whose size can grow without bound. As such, marks and measurements must be cleared out regularly, or disabled entirely, in long running processes to avoid running out of memory.
- **Everything is globally scoped**: With the User Timing API, any code that wishes to track performance measurements do so via a globally scoped …

Add @siteimprove/alfa-performance package

---

packages/alfa-rules/src/common/predicate/is-rendered.ts

`<iframe srcdoc="<p>Foo</p>" hidden />` was considering the `<p>` element as rendered because all its non-nested parents are…

Make content document of non-rendered elements also not rendered

---

packages/alfa-css/src/value.ts
packages/alfa-css/src/value/angle.ts
packages/alfa-css/src/value/color/hex.ts
packages/alfa-css/src/value/color/hsl.ts
packages/alfa-css/src/value/color/named.ts
packages/alfa-css/src/value/color/rgb.ts
packages/alfa-css/src/value/dimension.ts
packages/alfa-css/src/value/gradient/linear.ts
packages/alfa-css/src/value/image.ts
packages/alfa-css/src/value/integer.ts
packages/alfa-css/src/value/keyword.ts
packages/alfa-css/src/value/length.ts
packages/alfa-css/src/value/number.ts
packages/alfa-css/src/value/numeric.ts
packages/alfa-css/src/value/percentage.ts
packages/alfa-css/src/value/position.ts
packages/alfa-css/src/value/shadow.ts
packages/alfa-css/src/value/string.ts
packages/alfa-css/src/value/transform/matrix.ts
packages/alfa-css/src/value/transform/perspective.ts
packages/alfa-css/src/value/transform/rotate.ts
packages/alfa-css/src/value/transform/scale.ts
packages/alfa-css/src/value/transform/skew.ts
packages/alfa-css/src/value/transform/translate.ts
packages/alfa-css/src/value/url.ts
packages/alfa-style/src/property/value/list.ts

In the line of #644, I figured `Value.JSON` could as well incorporate the type of value.
Not sure if we should extend further for sub-interfaces with common field (e.g. `format` for colours or `kind` for transforms).

Make `Value.JSON` optionally parametric

---

packages/alfa-selective/package.json
packages/alfa-selective/src/index.ts
packages/alfa-selective/src/selective.ts
packages/alfa-selective/test/selective.spec.ts
packages/alfa-selective/tsconfig.json
packages/tsconfig.json

Add @siteimprove/alfa-selective package

---

CHANGELOG.md
packages/alfa-rules/src/sia-r65/rule.ts
packages/alfa-rules/test/sia-r65/rule.spec.tsx

Accept color difference as a valid focus indicator in SIA-R65

---

packages/alfa-aria/scripts/attributes.js
packages/alfa-aria/scripts/roles.js
packages/alfa-aria/src/attribute/data.ts
packages/alfa-aria/src/role.ts
packages/alfa-aria/src/role/data.ts
packages/alfa-rules/src/sia-r42/rule.ts

The fact that we're currently tracking the ARIA working draft came up during a customer call as something that was causing issues. The editors draft contains several improvements that UAs and ATs have already picked up, but many of these Alfa will flag as issues.
The changes are breaking as `Role#requiredParent()` now returns `Iterable<Iterable<Role.Name>>` due to ARIA now also listing nested parent requirements, such as `foo` "contained by" `bar`, as needed.

Track ARIA editors draft

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/src/node.ts
packages/alfa-aria/src/role.ts
packages/alfa-aria/test/name.spec.tsx
packages/alfa-aria/test/node.spec.tsx
packages/alfa-rules/src/common/predicate/has-accessible-name.ts
packages/alfa-rules/src/common/predicate/has-explicit-role.ts
packages/alfa-rules/src/common/predicate/has-heading-level.ts
packages/alfa-rules/src/common/predicate/has-implicit-role.ts
packages/alfa-rules/src/common/predicate/has-role.ts
packages/alfa-rules/src/common/predicate/is-ignored.ts
packages/alfa-rules/src/sia-r10/rule.ts
packages/alfa-rules/src/sia-r15/rule.ts
packages/alfa-rules/src/sia-r16/rule.ts
packages/alfa-rules/src/sia-r41/rule.ts
packages/alfa-rules/src/sia-r42/rule.ts
packages/alfa-rules/src/sia-r57/rule.ts
packages/alfa-rules/src/sia-r67/rule.ts
packages/alfa-rules/src/sia-r68/rule.ts
packages/alfa-rules/src/sia-r81/rule.ts

While looking into CPU profiles over the past couple of months, one thing that consistently came out near the top of our cycle spend was handling of branched values during accessibility tree construction. The only thing we currently account for, however, is a bug in Firefox related to case sensitive `role` attributes. 
The plan has for a long time been to expand our coverage of these browser differences, but for lack of actually presenting them in the Siteimprove platform this work has kept getting pushed. As the release of the new Accessibility product has also shown, many customers are already finding it difficult enough to understand some of the more advanced rules that are now available. Adding an additional layer of complexity that is results dependant on possibly branched values …

Unbranch ARIA types

---

packages/alfa-aria/src/name.ts
packages/alfa-aria/src/node.ts
packages/alfa-rules/src/common/predicate/is-rendered.ts
packages/alfa-style/src/property/display.ts
packages/alfa-style/test/property/display.spec.tsx
packages/alfa-style/tsconfig.json

These changes are breaking as the specified and computed type of the `display` property has changed from a plain tuple type to the `Tuple` class.
Resolves #761.

Implement remaining `display` grammar

---

packages/alfa-rules/src/sia-r62/rule.ts
packages/alfa-rules/test/sia-r62/rule.spec.tsx

Due to [Privacy restriction on `:visited`](https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector) the only things that can change between a `:link` and a `:visited` is the colour of a few properties, and not even the transparency.
R62 doesn't check colour (except `background-color`), only presence and transparency.
Therefore, in its current state, the only case where
* the second expectation of R62 fails
* BUT the first is passing
* AND this is not a false positive due to #708 
is variations on
```
<style>
p { background-color: white }
:any-link { text-decoration: none }
:link { background-color: red }
:visited { background-color: white }
</style>
```
So, I think it's safe to remove the second expectation as almost everything it catches that isn't a false …

Remove second expectation from R62

---

packages/alfa-css/src/syntax/nth.ts
packages/alfa-selector/src/selector.ts

Resolves #768 
Add `#equals` and `#toString` to functional pseudo-classes and pseudo-elements since they cannot just rely on their parent class' methods.

Implement pseudo classes equality

---

packages/alfa-rules/src/sia-r62/rule.ts
packages/alfa-rules/test/sia-r62/rule.spec.tsx

Let SIA R62 accept a difference in `font-weight` with the container as a distinguishable feature for links.
This is a brittle and imperfect patch, and we need to consider this more cautiously as part of #775. This removes a large pain point for customers until we take further decision, and aligns with the text in the platform.
This is still hit by #777.
This creates false negatives in cases like
```html
<p>Lorem <span style="font-weight: bold">Text</span> ipsum <a style="text-decoration: none; font-weight: bold">Link</a></p>
```
where the link is not distinguishable from the span.

SIA R62: accept different font weight

---

packages/alfa-rules/src/sia-r14/rule.ts
packages/alfa-rules/src/sia-r42/rule.ts
packages/alfa-rules/test/sia-r14/rule.spec.tsx
packages/alfa-rules/test/sia-r42/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Extended diagnostic for R14, part of #381.
Test for R42, part of #759.

Extended diagnostic for R14

---

packages/alfa-style/src/property/background-size.ts
packages/alfa-style/src/property/background.ts
packages/alfa-style/test/property/background-size.spec.tsx
packages/alfa-style/tsconfig.json

Fix background size

---

packages/alfa-rules/test/sia-r12/rule.spec.tsx
packages/alfa-rules/tsconfig.json

SIA R12: Add Test

---

packages/alfa-rules/src/sia-r62/rule.ts
packages/alfa-style/src/index.ts
packages/alfa-style/src/property/text-decoration-thickness.ts
packages/alfa-style/src/property/text-decoration.ts
packages/alfa-style/test/property/text-decoration.spec.tsx
packages/alfa-style/tsconfig.json

Support CSS property `text-decoration-thickness`.

Support text-decoration-thickness

---

packages/alfa-rules/src/sia-r55/rule.ts
packages/alfa-rules/src/sia-r56/rule.ts

We actually want to send the role as part of the diagnostic to avoid frontend trying to recomputing it…

Pass roles as part of diagnostics in SIA-R55 and SIA-R56

---

packages/alfa-cli/bin/alfa/command/scrape/flags.ts
packages/alfa-cli/bin/alfa/command/scrape/run.ts
packages/alfa-scraper/src/archive.ts
packages/alfa-scraper/src/index.ts
packages/alfa-scraper/src/scraper.ts
packages/alfa-scraper/tsconfig.json

This pull request adds a new option `archive` in the `Scraper#scrape()` method that currently supports capturing an [MHTML](https://en.wikipedia.org/wiki/MHTML) archive of the page being scraped, similar to how screenshots can be captured with the `screenshot` option. It also adds two new flags to the CLI: `--archive` and `--archive-format`.
Archives can be a useful addition to screenshots for verifying the state of the page when scraped. It also provides a useful tool for performing additional manual inspection of the page.

Add `archive` option in `Scraper#scrape()`

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/test/node.spec.tsx

Resolves #799 
* Ignoring `<datalist>` because 
1. it's hard and costly to find if there is a correct `<input list="id">`
2. it's never rendered (I think), so always ignored 🤔 
3. let's keep it simple until it proves problematic…
* Ignoring checkboxes and radio buttons because:
1. the bit around the `checkedness` is mostly covered by the `checked` attribute (https://html.spec.whatwg.org/multipage/input.html#dom-input-checked) not fully, since it is the IDL attribute, but should be good enough.
2. the bit around the `indeterminate` IDL attribute looks like something we just can't handle currently…

Aria attributes depending on element

---

packages/alfa-rules/src/common/predicate.ts
packages/alfa-rules/src/common/predicate/has-computed-style.ts
packages/alfa-rules/src/common/predicate/is-clipped.ts
packages/alfa-rules/src/common/predicate/is-visible.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
packages/alfa-rules/tsconfig.json

Resolves #731 
Plus a bit a refactor/streamlining of `isVisible` and `isClipped`.

Make descendents of fully clipped nodes invisible

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/test/node.spec.tsx

A quantifier was incorrect and a referrer was missing when computing names of implicit `<label>` references.
Resolves #808

Fix naming from subtree and implicitly referenced `<label>` elements

---

docs/review/api/alfa-dom.api.md
package.json
packages/alfa-aria/test/node.spec.tsx
packages/alfa-dom/src/jsx-runtime.ts
packages/alfa-dom/src/jsx.ts
yarn.lock

This was actually already accepted, but the types weren't accounting for it and so neither was the code 🙈

Accept arbitrarily deeply nested children in `jsx()`

---

docs/review/api/alfa-css.api.md
packages/alfa-css/src/value/length.ts
packages/alfa-rules/src/common/expectation/get-colors.ts
packages/alfa-rules/test/sia-r69/rule.spec.tsx
packages/alfa-style/src/index.ts
packages/alfa-style/src/property/text-shadow.ts
packages/alfa-style/test/property/text-shadow.spec.tsx
packages/alfa-style/tsconfig.json

Resolves #743 
Plus add support for `text-shadow`.

SIA R66 and R69: return `cantTell` when encountering a text shadow

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/test/name.spec.tsx

Handle duplicate `id`s and `for` attributes in `Name.from()`

---

packages/alfa-rules/src/rules.ts
packages/alfa-rules/src/sia-r46/rule.ts
packages/alfa-rules/src/sia-r76/rule.ts
packages/alfa-rules/test/sia-r76/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Implement SIA R76

---

packages/alfa-rules/src/sia-r49/rule.ts
packages/alfa-rules/test/sia-r49/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Accept native `<video>` and `<audio>` controls in SIA-R49

---

docs/review/api/alfa-thenable.api.md
packages/alfa-thenable/package.json
packages/alfa-thenable/src/thenable.ts
packages/alfa-thenable/test/thenable.spec.ts
packages/alfa-thenable/tsconfig.json
yarn.lock

This pull request adds some additional helper functions for the `Thenable` type to maintain symmetry with `Promise` and `Future`. You might be wondering why we even have all these types as they can all seem like the same way to accomplish the same thing; asynchronous control flow.
The best way to reason about having 3 different types to achieve essentially the same thing is perhaps by comparing them to the `Iterable`, `Array`, and `Sequence` types as they have a lot in common:
- `Iterable` models sequences of values and `Thenable` models asynchronous control flow in a lazy, stack-unsafe manner by using the call stack. They provide excellent performance at the risk of blowing the stack.
- `Array` models sequences of values and `Promise` models asynchronous control flow in an eager, …

Add additional `Thenable` helpers

---

packages/alfa-media/src/media.ts
packages/alfa-media/test/media.spec.ts

Faulty logic was breaking the matching when the value was exactly at the range boundary.

Fix matching boundaries of media queries ranges

---

packages/alfa-rules/src/sia-r83/rule.ts

So that it can be used for typing Dory's marshalling functions.

SIA-R83: Export diagnostic

---

packages/alfa-wcag/src/criterion.ts

Usage:
```javascript
import { Conformance, Criterion } from "@siteimprove/alfa-wcag";
const contrast = Criterion.fromURI(
"https://www.w3.org/TR/WCAG/#contrast-minimum"
).get();
console.log(Conformance.isA()(contrast)); // false
console.log(Conformance.isAA()(contrast));  // true
console.log(Conformance.isAAA()(contrast));  // true
```

Add function to create a WCAG `Criterion` from its URI

---

docs/review/api/alfa-assert.api.md
packages/alfa-assert/src/assertion.ts
packages/alfa-assert/test/asserter.spec.ts
packages/alfa-assert/test/fixture/rule.ts

Resolves #1012 
Assertions now accept an oracle, and a way to filter out irrelevant `cantTell` outcomes (default is to remove all `cantTell` outcomes and keep all `failed` ones).

Devtools improvements

---

docs/review/api/alfa-dom.api.md
docs/review/api/alfa-rules.api.md
packages/alfa-dom/src/h.ts
packages/alfa-dom/src/jsx.ts
packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/attribute.ts
packages/alfa-dom/src/node/attribute/predicate/has-name.ts
packages/alfa-dom/src/node/comment.ts
packages/alfa-dom/src/node/document.ts
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/element/predicate/has-name.ts
packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
packages/alfa-dom/src/node/fragment.ts
packages/alfa-dom/src/node/text.ts
packages/alfa-dom/src/node/type.ts

Add a `path` property to DOM nodes JSON serialisation, to match EARL and SARIF ones.
Unfortunately, we can't make it mandatory because this serialisation is also our (input) interface with native DOM or Dory. Native DOM does not provide an easy way to find the node's path, and there is no need to change Dory for that.
Also adds some improved typing of nodes that are named (Element, Attribute, Type) and their serialisation.

Serialise `path` in DOM Nodes JSON

---

docs/review/api/alfa-act.api.md
docs/review/api/alfa-rules.api.md
packages/alfa-act/src/question.ts
packages/alfa-assert/test/fixture/rule.ts
packages/alfa-rules/src/common/expectation/media-text-alternative.ts
packages/alfa-rules/src/common/question.ts
packages/alfa-rules/src/sia-r15/rule.ts
packages/alfa-rules/src/sia-r23/rule.ts
packages/alfa-rules/src/sia-r24/rule.ts
packages/alfa-rules/src/sia-r25/rule.ts
packages/alfa-rules/src/sia-r33/rule.ts
packages/alfa-rules/src/sia-r39/rule.ts
packages/alfa-rules/src/sia-r41/rule.ts
packages/alfa-rules/src/sia-r48/rule.ts
packages/alfa-rules/src/sia-r49/rule.ts
packages/alfa-rules/src/sia-r55/rule.ts
packages/alfa-rules/src/sia-r69/rule.ts
packages/alfa-rules/src/sia-r81/rule.ts

In `Question`, replace the `message` field by a full blown `Diagnostic`.
Questions now need to be built wrapping the message in `Diagnostic.of` and the message can be accessed by replacing `question.message` with `question.diagnostic.message`.

Replace Questions' message by Diagnostic

---

docs/review/api/alfa-act.api.md
docs/review/api/alfa-rules.api.md
packages/alfa-act/src/question.ts
packages/alfa-assert/test/fixture/rule.ts
packages/alfa-rules/src/common/act/question.ts
packages/alfa-rules/src/common/expectation/media-text-alternative.ts
packages/alfa-rules/src/sia-r15/rule.ts
packages/alfa-rules/src/sia-r23/rule.ts
packages/alfa-rules/src/sia-r24/rule.ts
packages/alfa-rules/src/sia-r25/rule.ts
packages/alfa-rules/src/sia-r33/rule.ts
packages/alfa-rules/src/sia-r39/rule.ts
packages/alfa-rules/src/sia-r41/rule.ts
packages/alfa-rules/src/sia-r48/rule.ts
packages/alfa-rules/src/sia-r49/rule.ts
packages/alfa-rules/src/sia-r55/rule.ts
packages/alfa-rules/src/sia-r81/rule.ts

While working on #1033 I realised we actually need both a message and diagnostic for questions and cannot simply use the message inside the diagnostic 😕 For two reasons:
1. We still need to ask the question, even if we explain why we need it. I.e. we need to send ("What is the color?", ("I couldn't find because of a background image", `background-image: url(foo)`)) which is both a message and a diagnostic.
This alone could be solved by nesting the diagnostic inside another one, or flattening in a `{message: "color?", reason: "background image", …}`-like object.
2. A convenient way to feed diagnostic to questions is to use `.answerIf` failure cases, since we'll mostly need these diagnostics when Alfa tried to get the answer itself and failed (i.e. we don't need a diagnostic for "Is the …

Separate message from diagnostic in questions

---

packages/alfa-rules/src/common/predicate/is-clipped.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx

Resolves #887 (again 🙄 )
Plus corrects a typo in `isClippedByMasking` 🙈

`isClipped`: recurse to offset parent and fix masking comparison

---

packages/alfa-rules/src/common/act/expectation.ts

In #286, we allowed expectation to be `Option.Maybe` instead of just `Option` ([this change](https://github.com/Siteimprove/alfa/pull/286/files#diff-5e38584e1360a99b4db83cc874a7c2eb41f343d6b80484b462280cb95df8bc21L254)) This made `toExpectation` completely useless since it was doing this transformation, but we never cleaned it 🙈 
Note that now, the cases where the thunks are inexpensive (e.g. static) could be rewritten from `expectation(test, () => Outcomes.OK, () => Outcomes.KO)` to `test ? Outcomes.OK : Outcomes.KO`, but it probably still make sense to keep wrapping in the `expectation helper for the sake of keeping things similar, and of course there are cases where the thunks are expensive (notably if they contain questions) and thus should be frozen as continuations…

Simplify expectation helper

---

.github/workflows/integrate.yml

We've seem quite a few failures on the windows build lately, e.g. [this one](https://github.com/Siteimprove/alfa/runs/5419661399?check_suite_focus=true). Given the error message 
```shell
Run yarn build
yarn build
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Error: Process completed with exit code 1.
```
I do suspect this might have something to do with the change of windows target of https://github.com/actions/virtual-environments/issues/4856
Trying to rollback to `windows-2019` to see if it ease the problem.

Use windows-2019 as integrate target

---

packages/alfa-rules/src/sia-er62/rule.ts
packages/alfa-rules/test/sia-er62/rule.expectation.spec.tsx

SIA-ER62: `background-image` should ignore transparent link element

---

docs/review/api/alfa-selector.api.md
packages/alfa-rules/test/sia-r65/rule.spec.tsx
packages/alfa-selector/src/selector.ts

We incorrectly understood that `:focus-visible` was an addition to `:focus`, and that it would only apply in a combination `:focus:focus-visible`.
It turns out that `:focus-visible` already matches a subset of `:focus` (based on UA choices).
This PR changes the `matches` of `FocusVisible` from "always" to "same as `Focus`" to reflect that.

Change :focus-visible to match :focus elements

---

packages/alfa-rules/src/sia-er62/rule.ts
packages/alfa-rules/test/sia-er62/rule.applicability.spec.tsx

Links gathering wasn't correct in case of nested paragraphs.
Even though nested `<p>` elements are not allowed, they do appear. Additionally, roles can be overwritten…

ER62: fixes some corner cases with nested paragraphs

---

packages/alfa-aria/src/node.ts
packages/alfa-aria/test/node.spec.tsx
packages/alfa-style/src/node/predicate/is-rendered.ts

Do not expose elements with a non-rendered ancestor, even if referenced by `aria-owns`

---

packages/alfa-css/src/syntax/lexer.ts
packages/alfa-css/test/syntax/lexer.spec.ts

When [consuming a hash symbol](https://github.com/Siteimprove/alfa/blob/edf852a8ccaec61fb8c659c9bb22e8b24db377dd/packages/alfa-css/src/syntax/lexer.ts#L559), we immediately [increased the index](https://github.com/Siteimprove/alfa/blob/edf852a8ccaec61fb8c659c9bb22e8b24db377dd/packages/alfa-css/src/syntax/lexer.ts#L560) in the string to start looking for an identifier from the next character.
However, when this lookup fails, we return a delimiter by [incrementing the index again](https://github.com/Siteimprove/alfa/blob/edf852a8ccaec61fb8c659c9bb22e8b24db377dd/packages/alfa-css/src/syntax/lexer.ts#L572). This resulted in skipping the character after a delimiter 🙈 
(the PR contains an unrelated reformat of the full file, I assume because it was last touched before some updates in prettier …

Fix CSS lexer dropping character after hash delimiter

---

packages/alfa-rules/src/sia-r78/rule.ts
packages/alfa-rules/test/sia-r78/rule.spec.tsx

Resolves #1039, resolves #1138 
Adapt to the latest Sanshikan version.

SIA-R78: Only accept accessible content between accessible headings

---

docs/review/api/alfa-aria.api.md
packages/alfa-aria/src/dom/dom.ts
packages/alfa-aria/src/dom/predicate/has-non-default-role.ts
packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/index.ts
packages/alfa-aria/tsconfig.json
packages/alfa-rules/src/sia-r16/rule.ts
packages/alfa-rules/test/sia-r16/rule.spec.tsx

Resolves #949 
See https://github.com/Siteimprove/sanshikan/pull/249

SIA-R16: only apply to explicit role

---

docs/review/api/alfa-rules.api.md
packages/alfa-rules/src/common/act/diagnostic.ts
packages/alfa-rules/src/sia-r53/rule.ts
packages/alfa-rules/test/sia-r53/rule.spec.tsx

Resolves #1187 
So far, only for storing in diagnostic for easier investigation.

Export previous heading in R53 diagnostic

---

docs/review/api/alfa-array.api.md
packages/alfa-array/src/array.ts
packages/alfa-rules/src/sia-r62/diagnostics.ts

```typescript
type Foo: {foo: number}
type Bar: {bar: string}
const comparer: Comparer<Foo> = (a, b) => Comparable.compareNumber(a.foo, b.foo);
const source: Array<Foo & Bar> = []
const dest = source.sortWith(comparer);
```
This used to lost the fact that the array contains `Foo & Bar` and only return an `Array<Foo>` because the same type was used for the array and the comparer. Now we can use a comparer on a super-type and keep the narrow type on the array.

Improve typing of `Array.sortWith`

---

docs/review/api/alfa-formatter.api.md
packages/alfa-formatter-earl/package.json
packages/alfa-formatter-earl/src/earl.ts
packages/alfa-formatter-earl/tsconfig.json
packages/alfa-formatter-json/src/json.ts
packages/alfa-formatter-sarif/src/sarif.ts
packages/alfa-formatter/package.json
packages/alfa-formatter/src/formatter.ts
packages/alfa-formatter/tsconfig.json
yarn.lock

In #1167 we were a bit too eager in making the formatter asynchronous, plus using a `Promise` rather than a `Future` prevented the formatters to be used as `Handler` in an `Assertion` 🙈 
This allow both synchronous and asynchronous (with `Future`) formatters.

Allow formatters to be synchronous

---

docs/review/api/alfa-array.api.md
docs/review/api/alfa-collection.api.md
docs/review/api/alfa-iterable.api.md
docs/review/api/alfa-list.api.md
docs/review/api/alfa-sequence.api.md
docs/review/api/alfa-slice.api.md
packages/alfa-array/src/array.ts
packages/alfa-collection/src/collection.ts
packages/alfa-iterable/src/iterable.ts
packages/alfa-list/src/list.ts
packages/alfa-sequence/src/cons.ts
packages/alfa-sequence/src/sequence.ts
packages/alfa-slice/src/slice.ts

```typescript
type Foo = { foo: number };
type Bar = { foo: number; bar: string };
function FooComparer(a: Foo, b: Foo): Comparison {
return Comparable.compareNumber(a.foo, b.foo);
}
function sortFoo(array: Array<Foo>): Array<Foo> {
return Array.sortWith(array, (a, b) => FooComparer(a, b));
}
function sortBar(array: Array<Bar>): Array<Bar> {
return Array.sortWith(array, (a, b) => FooComparer(a, b));
}
```
Before #1189, `sortBar` wasn't typable because `sortWith` was always returning the type of the comparer (`Array<Foo>`).
After #1189, `sortFoo` becomes untypable because `sortWith` was always expecting a type parameter `T` and would here infer it as `unknown` so `a` and `b` would be typed as `unknown`.
This let `sortWith` default to the older version and thus accept both types.

Keep subtype in collections with .sortWith

---

docs/review/api/alfa-css.api.md
packages/alfa-css/src/value/calculation.ts
packages/alfa-style/src/property/font-size.ts
packages/alfa-style/src/property/line-height.ts
packages/alfa-style/src/property/outline-offset.ts
packages/alfa-style/src/property/outline-width.ts
packages/alfa-style/test/property/outline.spec.tsx
packages/alfa-style/tsconfig.json

Part of #1202 which has caused problem in DEV-13509.

Support calculation in `outline-*`

---

docs/review/api/alfa-selector.api.md
packages/alfa-selector/package.json
packages/alfa-selector/src/context.ts
packages/alfa-selector/src/selector.ts
yarn.lock

Both of these selectors need to look into the full sub-tree to decide a match, so caching the computation.
Extra optimisation by adding an early escape break if nothing is hovered/focused in the context, since this is by far the most frequent case.

Cache `:hover` and `:focus-within` selector matching

---

packages/alfa-style/src/node/predicate/is-visible.ts
packages/alfa-style/test/node/predicate/is-visible.spec.tsx

The test was only made for `Element`, not `Text`, resulting in `Text` whose parent has `visibility: hidden` to be considered visible 🙈

Fix `isVisible` check on `visibility` property

---

packages/alfa-style/src/style.ts
packages/alfa-style/test/style.spec.tsx

Resolves DEV-13646
When encountering CSS variables with a fallback `var(--variable-name, fallback)`, we were incorrectly using the fallback before searching whether the variable is defined on an ancestor. This swaps the order of the operations.

Fix CSS variable substitution inheritance

---

packages/alfa-style/src/node/predicate/is-visible.ts
packages/alfa-style/test/node/predicate/is-visible.spec.tsx

Positions (`top`, `bottom`, `left`, `right`) are relative to the corresponding side, so a value of 0 on all does actually stretch the element.

Fix detection of stretched elements

---

packages/alfa-rules/src/sia-r64/rule.ts

Following https://github.com/act-rules/act-rules.github.io/pull/1640

SIA-R64: Remove mapping to 2.4.6

---

packages/alfa-scraper/test/scraper.spec.ts

The test for immediate location change seems a bit unstable in the actions, adding a small delay to give time for the location change to actually happen 🤞

Add delay to Scraper test to improve stability

---

docs/review/api/alfa-rules.api.md
packages/alfa-rules/src/rules.ts
packages/alfa-rules/src/sia-r110/rule.ts
packages/alfa-rules/src/sia-r21/rule.ts
packages/alfa-rules/test/sia-r110/rule.spec.tsx
packages/alfa-rules/test/sia-r21/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Following https://github.com/Siteimprove/sanshikan/pull/276
R21 is now only a best practice, since `role="btn button"` is not a WCAG failure but definitely a code smell.
R110 is the less strict version, requiring at least one valid token (rather than only valid tokens).

Downgrade SIA-R21, introduce SIA-R110

---

docs/review/api/alfa-act.api.md
packages/alfa-act/src/outcome.ts

Revert a breaking change accidentally introduced in #1318 where the property (and JSON) accessor for `Outcome` was changed from `outcome` to `value`.
The internal enum type is still named `Outcome.Value`, and `Outcome#outcome` ranges over it, mimicking the vocabulary used in EARL.

Revert `Outcome` property (and JSON) accessor from `value` back to `outcome`.

---

packages/alfa-rules/src/common/expectation/contrast.ts
packages/alfa-rules/test/sia-er69/rule.spec.tsx

When asking about `ignored-interposed-elements`, only ask about the ones encountered until the first different problem (image, non-static ancestor, …)
The reasoning is that whatever the answer is for further interposed elements, Alfa will still need to ask because of the other problem. Since we do not handle other `getColors` separately, this result in a `background-colors` question which is final, u.e. we never look at the other interposed elements and asking about them brings no value.

SIA-R66, R69: Only report interposed elements until another problem is encountered

---

packages/alfa-style/src/property/line-height.ts
packages/alfa-style/test/property/line-height.spec.tsx

Resolves #1323
When `line-height` is specified as a percentage, it's computed based on the elements `font-size` rather than that of its parent.

Compute line-height from percentage of font-size of self instead of from parent

---

README.md
docs/guides/README.md
docs/guides/writing-a-parser.md

This PR adds one guide, the folder structure and a link to the guide folder on the root README.md

Add guide on writing a parser

---

docs/review/api/alfa-selector.api.md
packages/alfa-selector/src/selector.ts
packages/alfa-selector/test/selector.spec.tsx

Resolves #1347
Updated the pseudo class parser to parse the `:host` selector.

Parse `:host` pseudo-class selector

---

docs/review/api/alfa-parser.api.md
packages/alfa-css/src/syntax/token.ts
packages/alfa-css/test/value/color/rgb.spec.ts
packages/alfa-css/tsconfig.json
packages/alfa-parser/src/parser.ts

Resolves #1291 
Update `parseWhitespace` so that it accepts one or more whitespace tokens to allow for the possibility that the lexer didn't manage to collapse all whitespace prior to the parsing. This might affect performance due to the extra check for more whitespaces and since this affects all users of the parser. If the performance hit is deemed unacceptable, we will explore other solutions.

Update whitespace parser to parse one or more

---

packages/alfa-rules/src/sia-r16/rule.ts
packages/alfa-rules/test/sia-r16/rule.spec.tsx

Resolves #1340 
Element with role `combobox` and missing `aria-controls` now passes SIA-R16 regardless of the state of `aria-expanded`. In the future we might refine this so that it won't pass when the combobox is open.

SIA-R16: Make `aria-controls` optional for role `combobox`

---

packages/alfa-dom/package.json

Use an export map for the [package entry point](https://nodejs.org/api/packages.html#package-entry-points) of `alfa-dom`.
This is especially needed for `jsx-runtime` due to the way that `jsxImportSource` option works in `tsconfig.json`: https://github.com/microsoft/TypeScript/issues/41623#issuecomment-734050495
This is a breaking change since it reduce the exported API. Some import path to internal files won't work anymore (which is actually a good thing to reduce footprint and enforce better modularity and separation of concerns).

alfa-dom: Use exports map

---

packages/alfa-css/src/syntax/token.ts
packages/alfa-css/test/syntax/token.spec.ts
packages/alfa-css/tsconfig.json

Fix to a bug uncovered after the release of [v0.60.0](https://github.com/Siteimprove/alfa/releases/tag/v0.60.0) where parsing whitespace could sometimes go into an infinite loop because of incorrect use of the `Slice` type. More specifically, when parsing an empty slice of an array, with more whitespace tokens in the array after the end of the slice, the parser would try to parse the whitespace after the slice and return the same empty array to be parsed again. This caused the bug because we now parse an unlimited number of whitespaces, instead of just one.

Fix bug in whitespace parser due to incorrect use of `Slice` type

---

packages/alfa-rules/src/sia-r13/rule.ts
packages/alfa-rules/test/sia-r13/rule.spec.tsx

SIA-R13: ignore `<iframe>` with negative `tabindex`

---

.changeset/purple-cats-applaud.md
packages/alfa-rules/src/common/predicate/is-aria-controls-optional.ts
packages/alfa-rules/src/sia-r16/rule.ts
packages/alfa-rules/src/sia-r19/rule.ts
packages/alfa-rules/tsconfig.json

Thus matching the actual behavior.

Rename `isAriaControlsRequired` -> `isAriaControlsOpitonal`

---

.github/workflows/alfa-release.yml
.github/workflows/release.yml

The step was omitted in the new release flow.

Regenerate API documentation in release action

---

.changeset/dry-apples-think.md
docs/review/api/alfa-act.api.md
docs/review/api/alfa-option.api.md
packages/alfa-act/src/rule.ts
packages/alfa-option/src/index.ts
packages/alfa-option/src/maybe.ts
packages/alfa-option/src/option.ts
packages/alfa-option/test/maybe.spec.ts
packages/alfa-option/tsconfig.json
packages/alfa-rules/src/common/act/expectation.ts

Resolves part of #1037 
Added `Maybe#toOption` and moved type out of `Option` namespace. This is a step in the direction of cleaning how we use the `Maybe` type in the rules.

Add `Maybe#toOption` and move out of `Option` namespace

---

docs/review/api/alfa-aria.api.md
docs/review/api/alfa-css.api.md
docs/review/api/alfa-selector.api.md
docs/review/api/alfa-style.api.md
package.json
packages/alfa-dom/src/h.ts
packages/alfa-style/src/style.ts
packages/alfa-tuple/src/tuple.ts
yarn.lock

Part of #1037.
Update to TS 5. There is still a type that cannot really be handled. This is partly due to some design choices in TS. So we have to help it and assert the correct type.

Typescript 5

---

.changeset/gold-pens-shave.md
.changeset/short-feet-drive.md
.changeset/short-rings-drop.md
docs/review/api/alfa-css.api.md
docs/review/api/alfa-style.api.md
packages/alfa-css/src/value/math-expression/math.ts
packages/alfa-style/package.json
packages/alfa-style/src/property/font-size.ts
packages/alfa-style/src/property/line-height.ts
packages/alfa-style/src/property/outline-offset.ts
packages/alfa-style/src/property/outline-width.ts
packages/alfa-style/src/property/value/compound.ts
packages/alfa-style/src/resolver.ts
packages/alfa-style/tsconfig.json
yarn.lock

Part of #1037 and #1202.
Create an abstraction for length, length-percentage, and number that can also be the result of calculations. The abstraction is easy to use in individual properties since it appears as a CSS value with a handy resolver to absolutize it.

Abstract Math calculation in style properties

---

.changeset/forty-wasps-grab.md
docs/review/api/alfa-css.api.md
docs/review/api/alfa-style.api.md
packages/alfa-css/src/value.ts
packages/alfa-css/src/value/numeric/length.ts
packages/alfa-css/test/value/numeric/length.spec.tsx
packages/alfa-rules/src/sia-r62/serialise.ts
packages/alfa-style/src/element/predicate/has-border.ts
packages/alfa-style/src/element/predicate/has-outline.ts
packages/alfa-style/src/property/border-top-width.ts
packages/alfa-style/src/property/letter-spacing.ts
packages/alfa-style/src/property/outline-offset.ts
packages/alfa-style/src/property/outline-width.ts
packages/alfa-style/src/property/value/compound.ts
packages/alfa-style/src/property/word-spacing.ts

Remove compound `Length` from `alfa-style`

---

.github/workflows/alfa-release.yml
.github/workflows/integrate.yml
.github/workflows/scan.yml
package.json
yarn.lock

Resolves #1356 
Update `package-dependency-graph`, and especially its `canvas` dependency to get a version with prebuilds for node 18 and 20.
Switch the Github actions matrices from node (14, 16) to (18, 20) as 14 is now in End of life, and 16 will be in September 2023.

Update package-dependency-graph and node

---

.changeset/silver-lions-smoke.md
packages/alfa-rules/src/sia-r75/rule.ts
packages/alfa-rules/test/sia-r75/rule.spec.tsx

In v0.65.0, there were two changes in behavior in R75.
In
```html
<div style="background: #eee; font-size: 0px">
<div style="font-size: 14px">world</div>
</div>
```
R75 was previously not applicable to the first `div` because the applicability explicitly checked for `font-size: 0px`. In v0.65.0 that check was removed and we instead expected `isVisible` to filter out elements with `font-size: 0px`. It doesn't however because the element is still be visible so the rule now applies to more elements than before. We decided that was acceptable in this case because the rules passes this element since the non-whitespace text content is large enough. We still rewrote the applicability so that it checks for "elements with visible text" in stead of "visible elements with text" as that is closer to …

Fix false positive bug in R75

---

.changeset/early-penguins-buy.md
.changeset/tidy-tips-walk.md
docs/review/api/alfa-css.api.md
docs/review/api/alfa-style.api.md
packages/alfa-css/README.md
packages/alfa-css/src/value/collection/list.ts
packages/alfa-css/src/value/collection/tuple.ts
packages/alfa-css/src/value/resolvable.ts
packages/alfa-css/src/value/shadow.ts
packages/alfa-css/src/value/value.ts
packages/alfa-css/test/value/shadow.spec.ts
packages/alfa-css/tsconfig.json
packages/alfa-style/README.md
packages/alfa-style/src/element/predicate/is-visible-shadow.ts
packages/alfa-style/src/property/box-shadow.ts
packages/alfa-style/src/property/text-shadow.ts
packages/alfa-style/test/property/box-shadow.spec.tsx

Calculatable `Shadow`

---

.changeset/rotten-socks-approve.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/query/element-id-map.ts
packages/alfa-rules/src/sia-r19/rule.ts
packages/alfa-rules/test/sia-r19/rule.spec.tsx

Back in [#1413](https://github.com/Siteimprove/alfa/pull/1413/files#diff-264574bd61bf30e83177f4f8f2af2e52fb9308fc56bfe55c7ab97e8fd3de115cL119-L131) we accidentally started searching for IDs in the subtree of the element, rather than its full tree (going to the root).
Fixing it.

SIA-R19: fix regression

---

.changeset/calm-camels-sell.md
.changeset/empty-ears-cheat.md
.changeset/lovely-bees-type.md
docs/review/api/alfa-selector.api.md
docs/review/api/alfa-style.api.md
packages/alfa-rules/src/common/expectation/contrast.ts
packages/alfa-rules/test/sia-r69/rule.spec.tsx
packages/alfa-selector/src/context.ts
packages/alfa-style/src/element/element.ts
packages/alfa-style/src/element/helpers/get-bounding-box.ts
packages/alfa-style/src/style.ts
packages/alfa-style/tsconfig.json

With this PR we now try to automatically answer the question of which interposed elements can be ignored using layout.
This will affect SIA-R66 and SIA-R69 so that they won't need to ask about ignored interposed descendants if layout is available.
In addition we prepare for getting device dependent boxes by adding a helper function `getBoundingBox(Element, Device)` to `alfa-style` even though we do not yet store information about which device was used to collect the boxes.

Use layout to improve handling of interposed elements

---

.changeset/nine-yaks-grow.md
packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

See https://github.com/w3c/accname/pull/167 for what accname seems to be planning.
Test page for browsers:
```html
<div id="div1" role="button">
<span slot="foo">Button in light, Slot in shadow</span>
</div>
<div id="div2"><span slot="foo">Button in shadow</span></div>
<script>
const shadowRoot1 = document
.getElementById("div1")
.attachShadow({ mode: "open" });
shadowRoot1.innerHTML = '<slot name="foo"></slot>';
const shadowRoot2 = document
.getElementById("div2")
.attachShadow({ mode: "open" });
shadowRoot2.innerHTML = '<button><slot name="foo"></slot></button>';
</script>
<div role="button"><iframe srcdoc="Hello"></iframe></div>
```

Name computation: Include shadow DOM in name from content

---

.changeset/stupid-lies-hang.md
packages/alfa-cascade/src/user-agent.ts
packages/alfa-rules/test/sia-dr66/rule.spec.tsx
packages/alfa-rules/test/sia-dr69/rule.spec.tsx
packages/alfa-rules/test/sia-r66/rule.spec.tsx
packages/alfa-rules/test/sia-r69/rule.spec.tsx

Previously, it defaulted to the initial transparent color, which could cause unintended behaviours when computing color contrast since unstyled `<button>` were essentially see-through 🙈

Use `buttonface` for UA `<button>`  background color

---

.changeset/old-badgers-drive.md
.changeset/purple-lemons-buy.md
packages/alfa-aria/src/feature.ts
packages/alfa-rules/src/sia-r70/rule.ts

`<hgroup>` was de-deprecated some times ago, and is present again in the standard, with new content model:
https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element

SIA-R70: Accept `<hgroup>`

---

.changeset/mighty-hounds-fly.md
config/validate-structure.json
docs/review/api/alfa-toolchain.api.md
packages/alfa-toolchain/package.json
packages/alfa-toolchain/src/validation/validate-all.ts
packages/alfa-toolchain/src/validation/validate-changesets.ts
packages/alfa-toolchain/tsconfig.json
yarn.lock

Avoid https://github.com/Siteimprove/alfa/commit/ea68e26852bd61c6e1cf74ea643d6f443d857b9c

Reject changesets with major bumps

---

scripts/test.mjs

Similarly to what we do for build, showing the tested file.
This is less perfect due to parallelism in tests, but at least shows it is not stuck 😄

Show tested file during `yarn test`

---

.changeset/metal-points-build.md
packages/alfa-performance/src/now.ts

With Node 19.0.0 and above, `Performance.of()` throws at run time, with a `this` binding error message. This is likely due to a change how `performance` is implemented there 🤔, maybe related to the update to V8 10.7.
Anyway, this boiled down to the way `now` was defined. Eta-expanding the calls let the correct `this` bindings happen and stuff works again.

Fix `this` binding issue in alfa-performance

---

packages/alfa-style/src/node/predicate/is-visible.ts

Resolves #1442
We no longer use a key of type `Option<Context>`  for the cache. If context is not supplied, the static instance from `Context.empty()` will be used.

Correctly cache `isVisible` in case of empty context

---

.changeset/dirty-lizards-explode.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/shadow.ts
packages/alfa-dom/src/node/text.ts
packages/alfa-dom/src/node/traversal/get-nodes-between.ts
packages/alfa-dom/test/traversal.spec.tsx
packages/alfa-dom/tsconfig.json

Fix a bug in tree traversal of flat tree for the rare case of comments being direct child of the shadow root.
We had an exception for elements and text to skip over the shadow root and return the host instead when querying the parent in the flat tree. This is correct because in the flat tree the shadow tree has been inserted by "merging" the host and the root. However, that exception was missing for comments, creating an issue in these cases.
Additionally fixed a missing tree traversal option in `getNodeBetween`.

Fix tree traversal of flat tree

---

.changeset/nine-cycles-search.md
packages/alfa-rules/src/sia-r69/rule.ts
packages/alfa-rules/test/sia-r69/rule.spec.tsx
yarn.lock

Resolves #1166
We just ignore text that only consists of punctuation.

Make punctuation-only texts inapplicable in R69

---

.changeset/curly-apes-repeat.md
.changeset/eighty-peaches-clean.md
docs/review/api/alfa-selector.api.md
packages/alfa-cascade/src/block.ts
packages/alfa-cascade/src/cascade.ts
packages/alfa-cascade/src/precedence/encapsulation.ts
packages/alfa-cascade/src/precedence/index.ts
packages/alfa-cascade/src/precedence/order.ts
packages/alfa-cascade/src/precedence/precedence.ts
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/test/block.spec.ts
packages/alfa-cascade/test/block.spec.tsx
packages/alfa-cascade/test/cascade.spec.tsx
packages/alfa-cascade/test/rule-tree.spec.ts
packages/alfa-cascade/test/selector-map.spec.tsx
packages/alfa-cascade/tsconfig.json
packages/alfa-selector/package.json
packages/alfa-selector/src/selector/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/host.ts
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
packages/alfa-selector/src/specificity.ts
packages/alfa-selector/test/pseudo-class.spec.tsx
packages/alfa-selector/tsconfig.json
packages/alfa-style/test/style.spec.tsx
yarn.lock

Part of #1533 
* Include encapsulation context in CSS cascade precedence.
* Correctly parse `:host` selector.
* Include "shadow rules" (i.e., `:host`, for now) from the shadow tree style sheet into shadow hosts' cascade.
* Exclude "shadow rules" from the cascade of the shadow tree they are defined on.
Given the nature of `:host`, full matching cannot be done within the selector itself but has to be delegated to the cascade (and selector map).

Support `:host` pseudo class

---

.changeset/gentle-tomatoes-draw.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/style/rule.ts
packages/alfa-dom/test/style.spec.ts
packages/alfa-dom/tsconfig.json

Randomly found that bug 🤷 
This notably caused https://github.com/Siteimprove/alfa/blob/main/packages/alfa-cascade/src/user-agent.ts#L40-L44 to not be considered as a User Agent rule due to the nesting, and therefore lose cascade versus important Author rules.

Fix ownership of rules

---

packages/alfa-aria/scripts/attributes.js
packages/alfa-aria/scripts/roles.js
packages/alfa-compatibility/scripts/browsers.js
packages/alfa-compatibility/scripts/features.js
packages/alfa-iana/scripts/languages.js
packages/alfa-wcag/scripts/criteria.js
packages/alfa-wcag/scripts/techniques.js

It seems that `prettier.format` has become async at some point.
Since we only use it in scripts that already fetch data and thus await it, this is not a big deal…
(also did reformat the code of these files…)

Await on `prettier.format`

---

.changeset/afraid-beers-share.md
packages/alfa-aria/scripts/name-testable-statements.js
packages/alfa-aria/src/name/name.ts
packages/alfa-aria/test/name-testable-statements.spec.tsx

Following what browsers do, elements with a `display: table-cell` get spaced when part of an accessible name (like `display: block`).
Also improve JSX generation from the testable statements to cater from JSX eagerly consuming spaces that are significant in HTML.

Accessible name: add spaces around table cell content

---

.changeset/sharp-chefs-glow.md
docs/review/api/alfa-string.api.md
packages/alfa-dom/src/node.ts
packages/alfa-rules/src/common/predicate.ts
packages/alfa-rules/src/common/predicate/is-whitespace.ts
packages/alfa-rules/src/sia-r1/rule.ts
packages/alfa-rules/src/sia-r14/rule.ts
packages/alfa-rules/src/sia-r4/rule.ts
packages/alfa-rules/src/sia-r5/rule.ts
packages/alfa-rules/src/sia-r57/rule.ts
packages/alfa-rules/src/sia-r62/rule.ts
packages/alfa-rules/src/sia-r7/rule.ts
packages/alfa-rules/src/sia-r74/rule.ts
packages/alfa-rules/src/sia-r80/rule.ts
packages/alfa-rules/test/sia-r1/rule.spec.tsx
packages/alfa-rules/test/sia-r74/rule.spec.tsx
packages/alfa-rules/tsconfig.json
packages/alfa-string/src/string.ts

#1566 introduced a regression by https://github.com/Siteimprove/alfa/pull/1566/files#diff-863bdebe0a5e147ff8d67f71ba769f2ef6f77109305a8a5965abce17ff6cfd00L333 and https://github.com/Siteimprove/alfa/pull/1566/files#diff-870662b9dc155c392cf92b48ac7305f02721520e4d37bfb3ef849bcf4e69f5daL65 making element with whitespace text suddenly having some "text content". This fixes it.
Plus refactor `isWhitespace` into `alfa-string`.

Fix detection of empty titles

---

.changeset/hip-plums-dance.md
docs/review/api/alfa-wcag.api.md
packages/alfa-wcag/scripts/criteria.js
packages/alfa-wcag/scripts/techniques.js
packages/alfa-wcag/src/criterion.ts
packages/alfa-wcag/src/criterion/data.ts
packages/alfa-wcag/src/technique/data.ts

* Update the data scripts to work with current version of WCAG 2.1 and 2.2.
* Update `Criterion` to output WCAG 2.2 data by default.
* Workaround 4.1.1 being deprecated in WCAG 2.2

Update to WCAG 2.2

---

.changeset/grumpy-olives-float.md
.changeset/wise-maps-end.md
packages/alfa-cascade/src/precedence/origin.ts
packages/alfa-cascade/src/precedence/precedence.ts
packages/alfa-cascade/src/rule-tree.ts
packages/alfa-cascade/test/rule-tree.spec.ts
packages/alfa-style/src/style.ts

With #1550, handling of `!important` was moved from `alfa-style` to `alfa-cascade`.
This collided with rule tree creation skipping over blocks with a know selector (physical identity), assuming it would contain the same declarations, since know a (DOM) block with both normal and important declaration would create two (cascade) blocks with the same selector but different importance.
Simply checking importance before skipping the blocks.

Do not drop `!important` declarations from mixed blocks

---

.changeset/slimy-socks-cry.md
packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
packages/alfa-rules/src/sia-r111/rule.ts
packages/alfa-rules/src/sia-r113/rule.ts
packages/alfa-rules/test/sia-r113/rule.spec.tsx

SIA-R111 and SIA-R113 applicability improvements

---

.changeset/shy-walls-know.md
packages/alfa-device/src/native.ts

Ịt turns out not only web extensions but also puppeteer (and presumably other) need inlined code to inject 🙄 
https://pptr.dev/guides/javascript-execution

Inline `Device.Native.fromWindow`

---

.changeset/strong-adults-clap.md
packages/alfa-dom/package.json
packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/element/predicate/is-suggested-focusable.ts
packages/alfa-dom/test/node.spec.tsx
packages/alfa-dom/tsconfig.json
yarn.lock

The comparison of tab indexes was flawed due using `Option.compareWith` which puts `None` before any `Some`.
This placed non-tabbable shadow host **before** the rest of the content, thus any tabbable inside a shadow tree were put before the rest.
This corrects the comparison.

Taborder fix

---

.changeset/six-numbers-raise.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/shadow.ts
packages/alfa-dom/src/node/type.ts
packages/alfa-dom/test/node.spec.tsx

I discovered that the options containing the device used to serialize the boxes of elements where not passed down in all cases when recursively serializing descendants, causing the box to only be serialized on the top elements. This PR fixes that.

Fix serialization of boxes

---

.gitignore
docs/review/api/alfa-toolchain.api.md
packages/alfa-toolchain/package.json
packages/alfa-toolchain/src/changeset/changelog-individual.cts
packages/alfa-toolchain/src/index.ts
packages/alfa-toolchain/src/tsconfig.json

It seems that changeset config doesn't manage to load its own ESM version and thus needs to load more CJS code.
Fortunately, it also seems that only one file is really impacted 🤞

Move changeset generator to CJS

---

.changeset/dull-beers-attend.md
packages/alfa-aria/scripts/attributes.ts
packages/alfa-aria/scripts/name-testable-statements.ts
packages/alfa-aria/scripts/roles.ts
packages/alfa-compatibility/scripts/browsers.ts
packages/alfa-compatibility/scripts/features.ts
packages/alfa-iana/scripts/languages.ts
packages/alfa-wcag/scripts/criteria.ts
packages/alfa-wcag/scripts/techniques.ts

In ESM, `__dirname` has been replaced by `import.meta.dirname`.
Somehow, TS doesn't complain on this 🙈 and since these are grabbing scripts, they are not actually run during tests.

Fix usages of `__dirname`

---

.changeset/happy-lions-tie.md
.changeset/sixty-trainers-sleep.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/query/inclusive-element-descendants.ts
packages/alfa-dom/src/node/query/index.ts
packages/alfa-dom/src/tsconfig.json
packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
packages/alfa-rules/src/common/dom/get-clickable-box.ts
packages/alfa-rules/src/common/predicate/has-sufficient-size.ts
packages/alfa-rules/src/sia-r111/rule.ts
packages/alfa-rules/src/sia-r113/rule.ts
packages/alfa-rules/src/tsconfig.json
packages/alfa-rules/test/sia-r111/rule.spec.tsx
packages/alfa-rules/test/sia-r113/rule.spec.tsx

A target might have an undersized bounding box while the clickable area is sufficiently sized if there is an element descendant (like an image) that is sufficiently sized.
In general we need the target size rules to rely on the clickable area and not the bounding box of a target. So we try to calculate the clickable area of an element which as the union the bounding boxes of an element and all its descendants., i.e. the smallest rectangle that contains all the bounding boxes. This can overshoot the actual clickable area if it's not rectangular.

Include descendants in clickable area computation

---

.changeset/shaggy-maps-give.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/test/node.spec.tsx

Resolves II-8077.
Adds (the serialization `id` of) the assigned slot when serializing `Element` with high verbosity.

Add `assignedSlot` to high verbosity serialization of elements

---

.changeset/dirty-horses-exist.md
packages/alfa-web/src/page.ts

With the previous situation, provided options completely overwrite default ones, i.e. when providing a verbosity the device needed to be provided again.

Improve handling of default options in `Page#toJSON`

---

.changeset/hungry-eyes-care.md
packages/alfa-rules/src/common/diagnostic/with-bad-elements.ts
packages/alfa-rules/test/common/diagnostic/with-bad-elements.spec.tsx
packages/alfa-rules/test/tsconfig.json

When `WithBadElements` diagnostic is serialized, we now serialize the erroneous elements the same way we do most other places in stead of returning their xpaths. This give the clients control over how the elements should be serialized (full object or only serializationId).

Serialize elements in `WithBadElements`

---

.changeset/neat-papayas-vanish.md
.changeset/rude-hornets-buy.md
packages/alfa-device/src/native.ts
packages/alfa-dom/src/native.ts
packages/alfa-dom/test/native.spec.tsx

This makes them more flexible, notably for script injection:
* `inject(fromWindow)` serialises `fromWindow` correctly but doesn't pass an argument.
* `inject(fromWindow, window)` requires to have a handle (living in nodeJS world) on the window (living in the injection world), this is usually possible for DOM nodes, but not always for the `window` object itself.
* `inject( () => fromWindow(window) )` does not "recursively" serialise `fromWindow` which thus does not exists in the injection world. It would require using a bundler, or pre-injecting the function, … None of these being very convenient.
Now, `inject(fromWindow)` will work, defaulting to `globalThis.window` which is the most frequent case. If another window is needed, it can still be passed around (but then need to be provided by …

Make arguments of `Native` functions optional

---

.changeset/ninety-ligers-fetch.md
.changeset/twenty-snails-tap.md
docs/review/api/alfa-style.api.md
packages/alfa-style/src/longhand.ts
packages/alfa-style/src/predicate/is-block-container.ts
packages/alfa-style/src/predicate/is-flex-container.ts
packages/alfa-style/src/predicate/is-grid-container.ts
packages/alfa-style/src/property/overflow-x.ts
packages/alfa-style/src/property/overflow-y.ts
packages/alfa-style/src/property/text-overflow.ts
packages/alfa-style/src/style.ts
packages/alfa-style/src/tsconfig.json
packages/alfa-style/test/common.ts
packages/alfa-style/test/property/overflow.spec.tsx
packages/alfa-style/test/property/text-overflow.spec.tsx
packages/alfa-style/test/tsconfig.json

Part of #955 
While we cannot fully support used values for stuff that depends on layout (e.g., `width: auto`) (nor really need to yet), we can at least return no used value when the property does not apply to the element.
This adds the support for used value, as well as computes it correctly for `overflow` and `text-overflow`. We may have other properties in the same case, but we'll handle that when needed.

Support used values

---

.changeset/soft-chairs-reflect.md
docs/review/api/alfa-style.api.md
packages/alfa-style/src/style.ts
packages/alfa-style/src/variable.ts
packages/alfa-style/test/variable.spec.ts

Fix a case where chained CSS variables were not fully resolved, depending on the iteration ordering of the `Map`…

CSS variable resolution

---

.changeset/perfect-rivers-watch.md
packages/alfa-rules/src/common/applicability/non-disabled-texts.ts
packages/alfa-rules/test/sia-r69/rule.spec.tsx

Make text in `<a aria-disabled="true">foo</a>` inapplicable to color contrast rules.
It previously was because the `<a>` element without `href` is **not** a `link`, hence not a `widget`, making it fall through the exception in Applicability.
See https://github.com/act-rules/act-rules.github.io/issues/2215

Improve disabled text detection

---

.changeset/pink-rings-admire.md
.changeset/quiet-donkeys-return.md
.changeset/slimy-geckos-clean.md
packages/alfa-cascade/src/user-agent.ts
packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Resolves https://github.com/Siteimprove/dory/pull/330#issuecomment-2404291123

R83: Improve constrainted size detection

---

.changeset/fuzzy-toys-turn.md
docs/review/api/alfa-dom.api.md
docs/review/api/alfa-tree.api.md
packages/alfa-dom/src/h.ts
packages/alfa-dom/src/jsx.ts
packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/attribute.ts
packages/alfa-dom/src/node/comment.ts
packages/alfa-dom/src/node/document.ts
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/fragment.ts
packages/alfa-dom/src/node/shadow.ts
packages/alfa-dom/src/node/text.ts
packages/alfa-dom/src/node/type.ts
packages/alfa-dom/test/h.spec.ts
packages/alfa-dom/test/node.spec.tsx
packages/alfa-rules/test/common/diagnostic/with-bad-elements.spec.tsx
packages/alfa-rules/test/sia-r41/rule.spec.tsx
packages/alfa-tree/src/tree.ts

This makes it a bit more general.

Rename `tree.Node#serializationId` to `tree.Node#internalId`.

---

.changeset/poor-hounds-perform.md
.changeset/shy-radios-sip.md
docs/review/api/alfa-string.api.md
packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-string/package.json
packages/alfa-string/src/string.ts
packages/alfa-string/test/string.spec.ts
packages/alfa-string/test/tsconfig.json
packages/alfa-string/tsconfig.json
yarn.lock

In https://github.com/Siteimprove/alfa/pull/1694 SIA-R83 started detecting soft wrap points in string and use them to detect whether a text node can wrap or not. It was then only acting on spaces.
A frequent use case in several languages is to have dashes as composite word separators. This PR accepts any punctuation which should also catch some incorrectly spaced sentences, …

SIA-R83: accept more breakpoints

---

packages/alfa-rules/src/sia-r44/rule.ts

SIA-R44 has proven to be performing poorly, most likely due to the cost of computing some style properties with a different device (hence without relying on caching), merely for finding out that they are not orientation dependent.
This should improve the performance of the common use case, by doing a first quick lookup through all the style rules and escaping early if there is no orientation media feature in any of the media rules.
See [this discussion](https://siteimprove.slack.com/archives/G0E9EH2AJ/p1730128127722729) for more details.

Escape SIA-R44 early if there is no orientation media query

---

.changeset/grumpy-games-fix.md
packages/alfa-rules/src/common/applicability/targets-of-pointer-events.ts
packages/alfa-rules/src/common/dom/get-clickable-box.ts

This PR fixes an issue in the clickable box computation where the bounding boxes of all descendants would be used. For invisible descendants their bounding boxes would be an empty rectangle located at (0, 0) and since we are letting the clickable area be the convex hull of the boxes (the smallest containing rectangle), this would give wildly incorrect clickable areas in some cases. This was uncovered after `<select>`s were made visible.
More work will be needed to refine how R111 and R113 use the clickable boxes for sizing and spacing detection.

Add filtering of visible descendants in clickable box computation

---

config/alfa-renovate.json

It seems that the token and host rules cannot be shared easily like that and each repo will need its own. Additionally, repos depending only on public packages can just use the npmjs packages that don't require a token.

Remove token from global Renovate config

---

.changeset/pretty-scissors-explode.md
.changeset/short-bees-behave.md
packages/alfa-css-feature/src/media/feature/discrete.ts
packages/alfa-css-feature/test/media.spec.ts
packages/alfa-device/src/device.ts

* Getting an unset preference on a device was returning its value, rather than a `Preference` object, making further computations incorrect.
* Testing media queries in the boolean context was done with a poorly parenthesised expression, resulting in incorrect tests (this was probably not impacting anything since all user preferences are defined with an explicit `booleanFalse`, except for `orientation` which cannot be unset).

Fix a couple of CSS feature bugs

---

.changeset/long-humans-jump.md
packages/alfa-applicative/package.json
packages/alfa-applicative/src/index.ts
packages/alfa-applicative/src/tsconfig.json
packages/alfa-collection/package.json
packages/alfa-collection/src/index.ts
packages/alfa-collection/src/tsconfig.json
packages/alfa-foldable/package.json
packages/alfa-foldable/src/index.ts
packages/alfa-foldable/src/tsconfig.json
packages/alfa-functor/package.json
packages/alfa-functor/src/index.ts
packages/alfa-functor/src/tsconfig.json
packages/alfa-mapper/package.json
packages/alfa-mapper/src/index.ts
packages/alfa-mapper/src/tsconfig.json
packages/alfa-monad/package.json
packages/alfa-monad/src/index.ts
packages/alfa-monad/src/tsconfig.json

Resolves #1732
The "missing" `main` in `package.json` is what DefiniteylTyped does ([example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/package.json)), so it should be good enough.

Make packages type-only

---

.changeset/tiny-pianos-travel.md
docs/review/api/alfa-result.api.md
packages/alfa-result/src/err.ts
packages/alfa-result/src/ok.ts
packages/alfa-result/src/result.ts
packages/alfa-result/test/result.spec.ts

Small improvement that would have helped for https://github.com/Siteimprove/alfa-integrations/pull/120/files#diff-4897711f57e3d63495da7d9ad4ad75a9613e906f4a6de9383fba63401d59bc8cR230-R235

Accept callbacks in `Result#*orElse` methods

---

.changeset/sour-balloons-sing.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/text.ts
packages/alfa-dom/test/node/text.spec.ts
packages/alfa-dom/test/tsconfig.json

The optional parameters `box` and `device` should have defaults.

Add defaults for `Text.of` optional parameters

---

.changeset/few-taxis-thank.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/style/rule/import.ts
packages/alfa-dom/test/style.spec.ts

The `rules` property of `ImportRule` does not use the private field `_rules` which is left unset. Instead it calls to `_sheet.rules`. The parent class however serializes the `_rules` field which is then empty in the serialized output. To fix this, we override the serialization in `ImportRule` to use the public `rules` property to serialize `_sheet.rules`.

Fix serialization of imported stylesheets

---

.github/dependabot.yml

This is a follow up to https://github.com/Siteimprove/alfa/pull/1787.
Only the root directory should be specified for monorepos, otherwise Dependabot will create duplicate PRs and not update the yarn.lock in one of them, which is invalid. See https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027

Fix duplicate Dependabot PRs

---

.changeset/vast-owls-post.md
packages/alfa-painting-order/src/painting-order.ts
packages/alfa-painting-order/test/painting-order.spec.tsx

This replaces one incorrect implementation with another incorrect implementation. This will incorrectly order sibling inline and block elements, but correctly order inline parents and block children which is more likely to stack on top of each other, making it more important to get the order right in those cases.
Resolves https://siteimprove-wgs.atlassian.net/browse/II-9309

Remove distinction between block and inline elements in painting order

---

.changeset/floppy-peaches-attack.md
packages/alfa-rectangle/package.json
packages/alfa-rectangle/src/rectangle.ts
packages/alfa-rectangle/src/tsconfig.json
yarn.lock

Limits the size of the result of subtracting rectangles because the current way of representing the result can become too big to fit into an array.
Ideally, we should find a better way to represent the difference of rectangles that doesn't need to break the rectangles into many smaller rectangles. We could look into rectilinear polygons: https://en.wikipedia.org/wiki/Rectilinear_polygon.

Limit rectangle subtraction

---

config/vitest.config.ts
config/vitest.workspace.ts
package.json
packages/alfa-rng/package.json
packages/alfa-test/package.json
yarn.lock

Workspaces has been deprecated and should be replaced by projects, but they are both broken and causing tests to fail. Therefore the vitest.workspace.ts has been deleted which means that tests won't be grouped by package for now.

Vitest 3.2
