Siteimprove/alfa

packages/alfa-aria/src/features/input.ts
packages/alfa-aria/src/features/select.ts
packages/alfa-aria/test/features/a.spec.tsx
packages/alfa-aria/test/features/area.spec.tsx
packages/alfa-aria/test/features/footer.spec.tsx
packages/alfa-aria/test/features/form.spec.tsx
packages/alfa-aria/test/features/header.spec.tsx
packages/alfa-aria/test/features/img.spec.tsx
packages/alfa-aria/test/features/input.spec.tsx
packages/alfa-aria/test/features/li.spec.tsx
packages/alfa-aria/test/features/link.spec.tsx
packages/alfa-aria/test/features/menu.spec.tsx
packages/alfa-aria/test/features/menuitem.spec.tsx
packages/alfa-aria/test/features/option.spec.tsx
packages/alfa-aria/test/features/section.spec.tsx
packages/alfa-aria/test/features/select.spec.tsx
packages/alfa-aria/test/features/td.spec.tsx
packages/alfa-aria/test/features/th.spec.tsx
packages/alfa-aria/test/get-role.spec.tsx

Added HTML feature tests. These can be considered blackbox tests as they are purely based on the documentation and not on the source code.

Add test cases for ARIA in HTML features

---

packages/alfa-aria/src/features/input.ts
packages/alfa-aria/test/features/area.spec.tsx
packages/alfa-aria/test/features/footer.spec.tsx
packages/alfa-aria/test/features/form.spec.tsx
packages/alfa-aria/test/features/header.spec.tsx
packages/alfa-aria/test/features/img.spec.tsx
packages/alfa-aria/test/features/input.spec.tsx
packages/alfa-aria/test/features/li.spec.tsx
packages/alfa-aria/test/features/link.spec.tsx
packages/alfa-aria/test/features/menu.spec.tsx
packages/alfa-aria/test/features/menuitem.spec.tsx
packages/alfa-aria/test/features/option.spec.tsx
packages/alfa-aria/test/features/section.spec.tsx
packages/alfa-aria/test/features/select.spec.tsx
packages/alfa-aria/test/features/td.spec.tsx
packages/alfa-aria/test/features/th.spec.tsx

This should fix the issues in alfa-aria that prevents the build from working correctly, as well as fixing failing tests.

Fixing the build and test issues on master

---

packages/alfa-html/src/alphabet.ts
packages/alfa-html/test/alphabet.spec.ts

This implements RCData tokenisation.

Closes #14: Implement HTML RCDATA tokenisation steps

---

packages/alfa-dom/src/matches.ts
packages/alfa-dom/test/matches.spec.tsx

Implement functional :host pseudo-class in Matches

---

packages/alfa-aria/src/roles/widgets/menu-item.ts
packages/alfa-dom/test/get-attribute.spec.tsx
packages/alfa-dom/test/get-button-type.spec.tsx
packages/alfa-dom/test/get-id.spec.tsx
packages/alfa-dom/test/has-attribute.spec.tsx
packages/alfa-dom/test/is-tabbable.spec.tsx

Made some tests to the Alfa-Dom package in order to, of course increase coverage, but also increase my knowledge of the code.

Adding tests to alfa dom

---

scripts/helpers/coverage.js
scripts/helpers/metrics/cyclomatic.js

I added a new metric to be used for testing. It functions in a similar way as the other metrics.
See comment about branching from wrong branch. Should be fine though, as it was all meant to go to master anyways.

Cyclomatic complexity metric

---

packages/alfa-css/test/parse.spec.ts
packages/alfa-css/test/units.spec.ts
packages/alfa-css/test/values.spec.ts

This does not include any tests of [packages/alfa-css/src/resolve-style.ts](https://github.com/Siteimprove/alfa/blob/master/packages/alfa-css/src/resolve-style.ts), as I think it is currently too complex for me to completely understand the intentions. This file could also possibly be refactored to be easier to maintain in the future.

Tests of alfa-css

---

packages/alfa-jsx/test/jsx.spec.tsx

This little test covers a small piece of untested code in JSX. Now JSX i 100% tested.

Adding a JSX test

---

scripts/helpers/coverage.js
scripts/helpers/text.js

Moved some functions from coverage.js to text.js. We talked about this a long long time ago @kasperisager and we agreed then that these functions should not be in coverage.js but in a separate file.

Moving functions to text.js

---

scripts/helpers/metrics/arithmetic.js
scripts/helpers/metrics/cyclomatic.js
scripts/helpers/metrics/logical.js

My pull request regarding issue #78 is bloated and full of small refactors, cleaning etc. I am breaking it up as it has become difficult to merge it with the current version of the master branch. Here is a small clean up of the test metrics.

Just a little bit of cleaning in the testing metrics

---

packages/alfa-rules/src/sia-r42/rule.ts
packages/alfa-rules/test/sia-r42/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Changes authored by @singingknight 
I don't know why he cannot push directly to the repo…

Fix SIA-R42

---

packages/alfa-rules/src/sia-r27/rule.ts
packages/alfa-rules/src/sia-r30/rule.ts
packages/alfa-rules/src/sia-r35/rule.ts
packages/alfa-rules/src/sia-r37/rule.ts
packages/alfa-rules/src/sia-r38/rule.ts
packages/alfa-rules/src/sia-r50/rule.ts
packages/alfa-rules/test/sia-r38/rule.spec.tsx

Quick'n'dirty patch on master.

Three valued logic

---

packages/alfa-aria/package.json
packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/node.ts
packages/alfa-aria/src/node/container.ts
packages/alfa-aria/src/node/element.ts
packages/alfa-aria/src/node/inert.ts
packages/alfa-aria/src/node/text.ts
packages/alfa-aria/tsconfig.json

Implement ARIA attribute mappings for HTML

---

packages/alfa-aria/src/node.ts

Resolve presentational role conflicts when building ARIA nodes

---

packages/alfa-aria/src/feature.ts
packages/alfa-table/package.json
packages/alfa-table/src/table.ts
packages/alfa-table/tsconfig.json

Cache table model

---

packages/alfa-rules/src/common/predicate/has-input-type.ts

Use Attribute#enumerate

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/get-name.ts

Using the new predicate to clean up code a bit.

Use hasName in alfa-aria

---

packages/alfa-rules/src/sia-r21/rule.ts
packages/alfa-rules/test/sia-r21/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Updating according to https://github.com/act-rules/act-rules.github.io/pull/1277 and https://github.com/Siteimprove/sanshikan/pull/100

Update sia r21

---

packages/alfa-rules/test/sia-r24/rule.spec.tsx
packages/alfa-rules/test/sia-r38/rule.spec.tsx
packages/alfa-rules/test/sia-r46/rule.spec.tsx
packages/alfa-rules/test/sia-r53/rule.spec.tsx
packages/alfa-rules/test/sia-r61/rule.spec.tsx

Just a clean up/unification on test names…

Unify test names

---

packages/alfa-selector/src/selector.ts

Implement pseudo selector parsing

---

packages/alfa-aria/src/node.ts
packages/alfa-aria/test/node.spec.tsx

Implement explicit `aria-owns` relations in the accessibility tree

---

packages/alfa-aria/src/name.ts

Step 2D of the name computation causes a combinatorial explosion for at least one input and has therefore been removed. Its removal has had no effect on the current test cases and so if we do find a case actually covered by this step, we'll deal with that if and when it becomes relevant.
I've also included a small optimisation to how visited nodes are stored. These are now kept in an array rather than a set and a linear scan is performed when testing if a node has already been visited. As it turns out, only very few nodes are usually visited during name computation and so the overhead of set operations becomes more expensive than just using an array.

Remove step 2D of the accessible name computation

---

packages/alfa-css/src/syntax.ts
packages/alfa-css/src/syntax/nth.ts
packages/alfa-css/src/syntax/token.ts
packages/alfa-css/test/syntax/nth.spec.ts
packages/alfa-css/tsconfig.json
packages/alfa-selector/src/selector.ts
packages/alfa-selector/test/selector.spec.ts
packages/alfa-selector/test/selector.spec.tsx
packages/alfa-selector/tsconfig.json

https://drafts.csswg.org/selectors/#structural-pseudos
Closes #57.
Closes #134.

Implement support for tree-structural pseudo-classes

---

CHANGELOG.md
packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

Ensure that `<select>` elements can be named by connected `<label>` elements

---

packages/alfa-rules/src/common/predicate/is-visible.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
packages/alfa-rules/tsconfig.json

Account for near-zero size clipped elements in `isVisible()`

---

packages/alfa-media/src/index.ts
packages/alfa-media/src/media.ts
packages/alfa-media/src/resolver.ts
packages/alfa-media/tsconfig.json
packages/alfa-style/src/index.ts
packages/alfa-style/src/resolver.ts

Implement matching for `(max|min)-(width|height)` features

---

packages/alfa-aria/src/node.ts
packages/alfa-aria/test/node.spec.tsx

Implement ARIA presentational role inheritance

---

packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Reverse `wrapsText()` conditions in SIA-R83

---

packages/alfa-style/src/property.ts
packages/alfa-style/src/property/text.ts
packages/alfa-style/test/property/text.spec.tsx

Support CSS text-indent property

---

packages/alfa-style/src/property.ts
packages/alfa-style/src/property/position.ts
packages/alfa-style/tsconfig.json

Support CSS `position` property

---

packages/alfa-rules/src/sia-r16/rule.ts
packages/alfa-rules/test/sia-r16/rule.spec.tsx

SIA R16: make inapplicable to ignored elements

---

packages/alfa-rules/src/sia-r45/rule.ts
packages/alfa-rules/test/sia-r45/rule.spec.tsx

SIA R45: ignore tables with presentational role

---

packages/alfa-rules/src/sia-r15/rule.ts
packages/alfa-rules/src/sia-r41/rule.ts
packages/alfa-rules/src/sia-r81/rule.ts
packages/alfa-rules/test/sia-r41/rule.spec.tsx
packages/alfa-rules/test/sia-r81/rule.spec.tsx
packages/alfa-rules/tsconfig.json

SIA R41 and R81: pass on definitely equivalent URLs.

---

packages/alfa-style/src/property.ts
packages/alfa-style/src/property/letter-spacing.ts
packages/alfa-style/src/property/text.ts
packages/alfa-style/src/property/word-spacing.ts
packages/alfa-style/tsconfig.json

Support CSS properties `letter-spacing` and `word-spacing`

---

packages/alfa-rules/src/sia-r84/rule.ts
packages/alfa-rules/test/sia-r84/rule.spec.tsx

Check for pairwise (`overflow-x`, `width`) and (`overflow-y`, `height`) handling in `isPossiblyScrollable()`

---

packages/alfa-selector/src/selector.ts

Improve performance of `:nth-*` selectors

---

packages/alfa-rules/src/sia-r46/rule.ts
packages/alfa-rules/test/sia-r46/rule.spec.tsx

SIA R46: Accept header assigned only to other header cells

---

packages/alfa-rules/src/common/predicate/is-visible.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
packages/alfa-rules/test/sia-r10/rule.spec.tsx

isVisible: take into account elements that are visible when empty

---

packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Improve `isPossiblyClipped()`

---

packages/alfa-css/src/value/position.ts
packages/alfa-css/test/value/position.spec.ts
packages/alfa-css/tsconfig.json
packages/alfa-style/src/property/background.ts
packages/alfa-style/test/property/background.spec.tsx

Needed for #591.
I've been hitting pretty strong with the test hammer as this is tricky and has a lot of corner cases so I want to limit the risks of regression…

Fix parsing of <position> CSS values

---

packages/alfa-rules/src/rules.ts
packages/alfa-rules/src/sia-r95/rule.ts
packages/alfa-rules/test/sia-r95/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Waiting for #653 for the test to pass.

Implement SIA-R95

---

packages/alfa-rules/src/sia-r48/rule.ts
packages/alfa-rules/src/sia-r49/rule.ts

Assume that `<audio>` elements have audio in SIA-R48 and SIA-R49

---

packages/alfa-rules/src/sia-r40/rule.ts

See https://github.com/Siteimprove/alfa/issues/298#issuecomment-770720526.

Limit SIA-R40 to explicit `region` roles

---

packages/alfa-act/package.json
packages/alfa-act/src/outcome.ts
packages/alfa-act/src/rule.ts
packages/alfa-act/tsconfig.json
packages/alfa-dom/package.json
packages/alfa-dom/src/node.ts
packages/alfa-dom/tsconfig.json
packages/alfa-formatter-sarif/package.json
packages/alfa-formatter-sarif/src/sarif.ts
packages/alfa-formatter-sarif/tsconfig.json
packages/alfa-rules/src/common/group.ts
packages/alfa-sarif/package.json
packages/alfa-sarif/src/index.ts
packages/alfa-sarif/src/sarif.ts
packages/alfa-sarif/src/serializable.ts
packages/alfa-sarif/tsconfig.json
packages/alfa-web/package.json
packages/alfa-web/src/page.ts
packages/alfa-web/tsconfig.json
packages/tsconfig.json
yarn.lock

Add @siteimprove/alfa-sarif package

---

CHANGELOG.md
packages/alfa-rules/src/sia-r65/rule.ts
packages/alfa-rules/test/sia-r65/rule.spec.tsx

Accept background color difference as a valid focus indicator in SIA-R65

---

CHANGELOG.md
packages/alfa-rules/src/common/predicate.ts
packages/alfa-rules/src/common/predicate/has-box-shadow.ts
packages/alfa-rules/src/sia-r65/rule.ts
packages/alfa-rules/test/sia-r65/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Accept box shadow as a valid focus indicator in SIA-R65

---

CHANGELOG.md
packages/alfa-css/src/value/length.ts
packages/alfa-css/src/value/unit.ts
packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Resolves #546.
Resolves #622.
Resolves #649.
Resolves #712.

Limit SIA-R83 to non-inline, non-font relative heights

---

CHANGELOG.md
packages/alfa-rules/src/common/predicate/is-transparent.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx

Fix `isTransparent()` for text nodes of transparent elements

---

CHANGELOG.md
packages/alfa-rules/src/sia-r84/rule.ts

Shout out to @annethyme for the heads up on this 👏

Don't consider `overflow: clip` as scrollable in SIA-R84

---

packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

Name computation: skip step 1 when descending

---

packages/alfa-rules/src/common/expectation/get-colors.ts
packages/alfa-rules/src/sia-r69/rule.ts
packages/alfa-rules/test/sia-r69/rule.spec.tsx

When getting layers of background, if we encounter a `background-size`, we bail out (and ask user for help) since we cannot determine if the background goes under text without a layout system.

Assume no background on size

---

packages/alfa-rules/test/sia-r17/rule.spec.tsx
packages/alfa-rules/tsconfig.json

SIA R17: add test

---

packages/alfa-rules/test/sia-r8/rule.spec.tsx
packages/alfa-rules/tsconfig.json

SIA-R8: Added tests

---

.github/workflows/integrate.yml

Trying to increase Nodejs heap size

---

packages/alfa-rules/src/common/predicate/has-border.ts
packages/alfa-rules/src/sia-r65/rule.ts
packages/alfa-rules/test/sia-r65/rule.spec.tsx

SIA R65: accept different border as focus indicator

---

.github/workflows/integrate.yml

Really increase heap size (#818 was setting back to the default value 🙄 )

Heap size problem and investigation.

---

packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

Accessible name: reject whitespace descendants

---

packages/alfa-rules/src/rules.ts

Forgot to activate them when implementing 🙈

Activate R55 and R56

---

.github/workflows/scan.yml

Revert "Bump github/codeql-action from 1.0.10 to 1.0.11"

---

docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node.ts
packages/alfa-rules/src/sia-r57/rule.ts
packages/alfa-rules/test/sia-r57/rule.spec.tsx

Pass text nodes in the first focusable element of the document in SIA-R57

---

packages/alfa-rules/src/sia-r75/rule.ts
packages/alfa-rules/test/sia-r75/rule.spec.tsx

Reject empty text nodes in SIA-R75

---

packages/alfa-aria/src/feature.ts

Map `input[value]` to `aria-valuenow`

---

packages/alfa-style/src/index.ts
packages/alfa-style/src/property/flex-direction.ts
packages/alfa-style/src/property/flex-flow.ts
packages/alfa-style/tsconfig.json

#932 missed that `flex-wrap` can also be set by the shorthand `flex-flow` 😢

SIA-R83: Support `flex-flow`

---

packages/alfa-rules/src/sia-r62/rule.ts
packages/alfa-rules/test/sia-r62/rule.spec.tsx
packages/alfa-rules/test/sia-r62/test.html

SIA-R62: ignores non link text with only whitespaces

---

packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx
packages/alfa-style/src/index.ts
packages/alfa-style/src/property/min-height.ts
packages/alfa-style/src/property/min-width.ts
packages/alfa-style/tsconfig.json

SIA-R83: accept ancestors with font relative dimensions as handling overflow

---

packages/alfa-rules/src/sia-r14/rule.ts
packages/alfa-rules/test/sia-r14/rule.spec.tsx

#938 made a regression on #648 😢 Reverting it.

Make R14 ignore non-perceivable text. Again

---

packages/alfa-aria/src/feature.ts
packages/alfa-rules/src/sia-r28/rule.ts
packages/alfa-rules/test/sia-r28/rule.spec.tsx
packages/alfa-rules/tsconfig.json

SIA-R28: Reject default name 'Submit Query' for inputs with type image

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/test/name.spec.tsx

We were failing [this example](https://act-rules.github.io/rules/59796f#passed-example-3)

Accept title attribute for name of input type=image

---

packages/alfa-rules/src/sia-er62/diagnostics.ts
packages/alfa-rules/src/sia-er62/rule.ts
packages/alfa-rules/src/sia-er62/serialise.ts
packages/alfa-rules/test/sia-er62/rule.spec.tsx

SIA-ER62: Merge R62 into ER62

---

packages/alfa-rules/src/sia-r47/rule.ts
packages/alfa-rules/test/sia-r47/rule.spec.tsx

SIA-R47: parses properties case insensitively

---

packages/alfa-rules/src/common/predicate/is-visible.ts
packages/alfa-rules/test/common/predicate/is-visible.spec.tsx

Resolves #985 
I needed it to streamline test cases for #1033 😄

Consider stretched elements as visible

---

docs/review/api/alfa-rules.api.md
packages/alfa-rules/src/index.ts
packages/alfa-rules/src/sia-er62/rule.ts
packages/alfa-rules/src/sia-er87/rule.ts
packages/alfa-rules/src/tags/index.ts
packages/alfa-rules/src/tags/stability.ts
packages/alfa-rules/src/tags/version.ts
packages/alfa-rules/tsconfig.json

Added version tag and marked ER62 and ER87 as version 2

---

package.json
packages/alfa-webdriver/package.json
yarn.lock

Update some dependencies

---

packages/alfa-rules/src/sia-r84/rule.ts
packages/alfa-rules/test/sia-r84/rule.spec.tsx

SIA-R84: Doesn't apply to browsing context container

---

docs/review/api/alfa-dom.api.md
docs/review/api/alfa-rules.api.md
packages/alfa-dom/src/node.ts
packages/alfa-dom/src/node/attribute.ts
packages/alfa-dom/src/node/comment.ts
packages/alfa-dom/src/node/document.ts
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/fragment.ts
packages/alfa-dom/src/node/shadow.ts
packages/alfa-dom/src/node/text.ts
packages/alfa-dom/src/node/type.ts

Expose DOM's nodes type

---

docs/review/api/alfa-media.api.md
packages/alfa-media/src/media.ts
packages/alfa-media/test/media.spec.ts

Media: queries `0` are accepted as `0px`

---

docs/review/api/alfa-act.api.md
packages/alfa-act/package.json
packages/alfa-act/src/diagnostic.ts
packages/alfa-act/src/interview.ts
packages/alfa-act/src/outcome.ts
packages/alfa-act/src/question.ts
packages/alfa-act/src/rule.ts
packages/alfa-act/tsconfig.json
packages/alfa-rules/src/common/dom/get-colors.ts
packages/alfa-rules/test/common/outcome.ts
packages/alfa-rules/test/sia-r66/rule.spec.tsx
packages/alfa-rules/test/sia-r69/rule.spec.tsx
yarn.lock

Add diagnostics in `cantTell` outcomes

---

docs/review/api/alfa-dom.api.md
packages/alfa-cascade/src/selector-map.ts
packages/alfa-dom/package.json
packages/alfa-dom/src/style/rule/import.ts
packages/alfa-dom/src/style/rule/media.ts
packages/alfa-rules/src/sia-r44/rule.ts
yarn.lock

Pre-parse media and import rules when building style tree

---

docs/review/api/alfa-act.api.md
packages/alfa-act/src/rule.ts

Small change related to [Dory](https://github.com/Siteimprove/dory/pull/128)

Changing object syntax for rule performance measuraments

---

packages/alfa-rules/src/sia-r17/rule.ts
packages/alfa-rules/src/sia-r21/rule.ts
packages/alfa-rules/src/sia-r90/rule.ts

Clean up mappings according to ACT rules changes

---

packages/alfa-aria/package.json
packages/alfa-aria/scripts/name-testable-statements.js
packages/alfa-aria/scripts/roles.js
packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name-testable-statements.spec.tsx
packages/alfa-aria/test/name.spec.tsx
packages/alfa-aria/tsconfig.json

Resolves #1186 
Auto generate test file from the [Accessible name testable statements](https://www.w3.org/wiki/AccName_1.1_Testable_Statements) with exceptions for the known bugs.
Fix a couple of small bugs.
The exceptions are handled in a way that once we fix the bug, the corresponding tests will fail and we can have a new look at them.

Include Accessible name testable statements

---

packages/alfa-rules/src/sia-r53/rule.ts

SIA-R53: Add getter for previous element in diagnostic

---

packages/alfa-aria/src/feature.ts
packages/alfa-aria/test/node.spec.tsx
packages/alfa-rules/test/sia-r42/rule.spec.tsx

Reverting the regression introduced in https://github.com/Siteimprove/alfa/pull/1185/commits/dea5d1758f2c0a46cc172fb0ed5c97ab81f05e0a 🙈

Map `<select>` to `listbox` all the time

---

packages/alfa-rules/src/sia-r57/rule.ts
packages/alfa-rules/test/sia-r57/rule.spec.tsx

R57: ignore incorrectly computed landmarks

---

packages/alfa-rules/src/common/dom/get-colors.ts
packages/alfa-rules/test/common/dom/get-colors.spec.tsx
packages/alfa-rules/test/sia-r66/rule.spec.tsx
packages/alfa-rules/test/sia-r69/rule.spec.tsx

Instead of stopping ut the first problem to resolve colors, keep going up the DOM tree and gather all the errors on the way.

Gather all problems in `getColors`

---

docs/review/api/alfa-aria.api.md
packages/alfa-aria/src/feature.ts
packages/alfa-aria/src/name.ts
packages/alfa-aria/test/name.spec.tsx

Fix `aria-labelledby` reference into hidden content

---

packages/alfa-rules/src/sia-r45/rule.ts
packages/alfa-rules/test/sia-r45/rule.spec.tsx
scratches/tsconfig.json

As per https://github.com/act-rules/act-rules.github.io/pull/1968 / https://github.com/Siteimprove/sanshikan/pull/268

SIA-R45: exclude tables with non-`table` role

---

docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/element/predicate/has-id.ts
packages/alfa-rules/src/sia-r19/rule.ts
packages/alfa-rules/test/sia-r19/rule.spec.tsx

Following ACT rules and https://github.com/Siteimprove/sanshikan/pull/274

SIA-R19: force required ID ref (list) to point to discoverable elements

---

docs/review/api/alfa-dom.api.md
packages/alfa-aria/src/dom/predicate/has-incorrect-role-without-name.ts
packages/alfa-aria/src/feature.ts
packages/alfa-aria/test/dom/predicate/has-incorrect-role-without-name.spec.tsx
packages/alfa-aria/tsconfig.json
packages/alfa-dom/src/node/element.ts
packages/alfa-dom/src/node/element/predicate.ts
packages/alfa-dom/src/node/element/predicate/is-scoped-to.ts
packages/alfa-dom/tsconfig.json

`hasIncorrectRoleWithoutName`: fix `<aside>` exception

---

packages/alfa-rules/src/common/applicability/audio.ts
packages/alfa-rules/src/common/applicability/role-attributes.ts
packages/alfa-rules/src/common/applicability/video.ts
packages/alfa-rules/src/sia-r110/rule.ts
packages/alfa-rules/src/sia-r21/rule.ts
packages/alfa-rules/tsconfig.json

Caching some shared Applicability, to shave a bit of time.

Cache applicability

---

packages/alfa-rules/src/sia-r78/rule.ts
packages/alfa-rules/test/sia-r78/rule.spec.tsx

SIA-R78: accept accordions (headings containing button/link)

---

.changeset/wet-actors-search.md
packages/alfa-rules/src/common/applicability/with-document-element.ts
packages/alfa-rules/src/sia-er87/rule.ts
packages/alfa-rules/src/sia-r1/rule.ts
packages/alfa-rules/src/sia-r109/rule.ts
packages/alfa-rules/src/sia-r59/rule.ts
packages/alfa-rules/src/sia-r61/rule.ts
packages/alfa-rules/src/sia-r70/rule.ts
packages/alfa-rules/src/sia-r87/rule.ts
packages/alfa-rules/tsconfig.json

Add `withDocumentElement` helper for Applicability

---

.changeset/cold-mugs-wave.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node/element/predicate/has-unique-id.ts
packages/alfa-rules/src/sia-r3/rule.ts

Remove useless void argument in hasUniqueId

---

.changeset/fifty-hats-protect.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/package.json
packages/alfa-dom/src/node/element/predicate/has-tab-index.ts
packages/alfa-dom/test/node/predicate/has-tab-index.spec.tsx
packages/alfa-dom/tsconfig.json
yarn.lock

`hasTabIndex`: accepts number(s) and add tests

---

.changeset/cold-mugs-wave.md
.changeset/gold-pens-shave.md
.changeset/purple-cats-applaud.md
.changeset/short-rings-drop.md
.changeset/sweet-days-reply.md
.changeset/ten-jars-think.md
.changeset/wet-actors-search.md

Cleaning up changesets before release.

Clean up changesets

---

.changeset/cool-moose-knock.md
packages/alfa-rules/src/sia-r78/rule.ts

SIA-R78: change scope to `Page`

---

.changeset/nice-socks-approve.md
packages/alfa-wcag/src/criterion.ts

Accept more URIs in `Criterion.fromURI`

---

.changeset/big-mice-fail.md
.changeset/orange-geese-raise.md
docs/review/api/alfa-css.api.md
packages/alfa-css/src/value/collection/list.ts
packages/alfa-css/src/value/collection/tuple.ts
packages/alfa-css/src/value/keyword.ts
packages/alfa-css/src/value/numeric/angle-percentage.ts
packages/alfa-css/src/value/numeric/angle.ts
packages/alfa-css/src/value/numeric/dimension.ts
packages/alfa-css/src/value/numeric/integer.ts
packages/alfa-css/src/value/numeric/length-percentage.ts
packages/alfa-css/src/value/numeric/length.ts
packages/alfa-css/src/value/numeric/number.ts
packages/alfa-css/src/value/numeric/numeric.ts
packages/alfa-css/src/value/numeric/percentage.ts
packages/alfa-css/src/value/resolvable.ts
packages/alfa-css/src/value/string.ts
packages/alfa-css/src/value/value.ts
packages/alfa-css/test/value/collection/list.spec.tsx
packages/alfa-css/test/value/collection/tuple.spec.tsx
packages/alfa-css/tsconfig.json
packages/alfa-style/src/property/background-repeat.ts
packages/alfa-style/src/property/background.ts
packages/alfa-style/src/property/border-image-slice.ts
packages/alfa-style/src/property/display.ts
packages/alfa-style/src/property/font-variant.ts

Support for calculatable collections of CSS values

---

.changeset/breezy-llamas-admire.md
packages/alfa-rules/src/sia-r83/rule.ts
packages/alfa-rules/test/sia-r83/rule.spec.tsx

Use layout to improve SIA-R83

---

.changeset/eighty-years-design.md
packages/alfa-rules/src/sia-r54/rule.ts
packages/alfa-rules/test/sia-r54/rule.spec.tsx

See https://github.com/Siteimprove/sanshikan/pull/295

SIA-R54: ignore empty elements

---

.changeset/tall-mails-kiss.md
packages/alfa-rules/src/sia-r10/rule.ts

SIA-R10: Accept `one-time-code`

---

.changeset/smart-weeks-bathe.md
docs/review/api/alfa-selector.api.md
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/where.ts
packages/alfa-selector/test/specificity.spec.ts
packages/alfa-selector/tsconfig.json

Add :where selector

---

.changeset/breezy-horses-smell.md
docs/review/api/alfa-selector.api.md
packages/alfa-selector/src/selector/selector.ts
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/nth-child.ts
packages/alfa-selector/src/selector/simple/pseudo-class/nth-last-child.ts
packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
packages/alfa-selector/test/nth-[last]-child.spec.tsx
packages/alfa-selector/test/pseudo-class.spec.tsx
packages/alfa-selector/tsconfig.json

Accept "of selector" syntax in `:nth-[last]-child` pseudo-classes

---

.changeset/rare-masks-lick.md
docs/review/api/alfa-selector.api.md
packages/alfa-cascade/README.md
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/test/cascade.spec.tsx
packages/alfa-selector/src/selector/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/host-context.ts
packages/alfa-selector/src/selector/simple/pseudo-class/host.ts
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/pseudo-class.ts
packages/alfa-selector/test/pseudo-class.spec.tsx
packages/alfa-selector/tsconfig.json

Support `:host-context` pseudo-class

---

.changeset/four-peaches-wave.md
docs/review/api/alfa-cascade.api.md
docs/review/api/alfa-dom.api.md
packages/alfa-cascade/src/block.ts
packages/alfa-cascade/src/cascade.ts
packages/alfa-cascade/src/precedence/index.ts
packages/alfa-cascade/src/precedence/layer.ts
packages/alfa-cascade/src/precedence/precedence.ts
packages/alfa-cascade/src/rule-tree.ts
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/test/block.spec.tsx
packages/alfa-cascade/test/cascade.spec.tsx
packages/alfa-cascade/test/precedence.spec.ts
packages/alfa-cascade/test/rule-tree.spec.ts
packages/alfa-cascade/test/selector-map.spec.tsx
packages/alfa-cascade/tsconfig.json
packages/alfa-dom/src/h.ts

Part of #945 
Add a model for layers, and tests for it. For now, only use fake layers.

Add model for CSS layers in `alfa-cascade`

---

.changeset/empty-jars-hang.md
.changeset/four-peaches-wave.md
.changeset/stale-numbers-shake.md
.changeset/stupid-camels-turn.md
docs/review/api/alfa-dom.api.md
docs/review/api/alfa-selective.api.md
packages/alfa-cascade/package.json
packages/alfa-cascade/src/precedence/layer.ts
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/test/block.spec.tsx
packages/alfa-cascade/test/cascade.spec.tsx
packages/alfa-cascade/test/common/index.ts
packages/alfa-cascade/test/layer.spec.ts
packages/alfa-cascade/test/selector-map.spec.tsx
packages/alfa-cascade/tsconfig.json
packages/alfa-dom/src/style/rule/import.ts
packages/alfa-dom/src/style/rule/layer.ts
packages/alfa-dom/src/style/rule/media.ts
packages/alfa-dom/src/style/rule/style.ts
packages/alfa-dom/src/style/rule/supports.ts
packages/alfa-selective/src/selective.ts
yarn.lock

Handle `@layer` rules when building `Cascade`.

---

.changeset/lucky-beers-tie.md
docs/review/api/alfa-rules.api.md
packages/alfa-rules/src/common/act/diagnostic.ts

Add export import of `WithBoundingBox`

---

.changeset/mean-glasses-hang.md
packages/alfa-rules/src/common/outcome/target-size.ts
packages/alfa-rules/src/sia-r111/rule.ts
packages/alfa-rules/src/sia-r113/rule.ts
packages/alfa-rules/test/sia-r111/rule.spec.tsx
packages/alfa-rules/test/sia-r113/rule.spec.tsx
packages/alfa-rules/tsconfig.json

Factor R111 and R113 outcome

---

.changeset/empty-boats-camp.md
.changeset/young-impalas-report.md
docs/review/api/alfa-css.api.md
docs/review/api/alfa-dom.api.md
package.json
packages/alfa-cascade/src/selector-map.ts
packages/alfa-cascade/test/selector-map.spec.tsx
packages/alfa-css-feature/src/supports/query.ts
packages/alfa-dom/src/h.ts
packages/alfa-dom/src/native.ts
packages/alfa-dom/src/style/rule/import.ts
yarn.lock

Support `layer` and `supports` condition in `@import` CSS rules

---

.changeset/empty-glasses-carry.md
.changeset/great-feet-nail.md
docs/review/api/alfa-cascade.api.md
docs/review/api/alfa-style.api.md
packages/alfa-cascade/src/index.ts
packages/alfa-cascade/src/precedence/encapsulation.ts
packages/alfa-cascade/src/precedence/origin.ts
packages/alfa-rules/test/sia-r62/serialise.spec.ts
packages/alfa-style/src/longhand.ts
packages/alfa-style/src/shorthands.ts
packages/alfa-style/src/style.ts
packages/alfa-style/test/common.ts
packages/alfa-style/test/style.spec.tsx

Css revert

---

packages/alfa-cascade/test/cascade.spec.tsx
packages/alfa-css/src/value/image/gradient/gradient.ts
packages/alfa-css/test/value/numeric/angle-percentage.spec.ts
packages/alfa-iana/scripts/languages.js
packages/alfa-style/src/property/border-image-outset.ts
packages/alfa-style/src/property/border-radius.ts

Resolves code scanning alerts. Not sure why it didn't block PRs earlier 🙈

Clean up code

---

.changeset/silly-wombats-do.md
docs/review/api/alfa-selector.api.md
packages/alfa-selector/src/common/is-link.ts
packages/alfa-selector/src/selector/simple/pseudo-class/any-link.ts
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/selector/simple/pseudo-class/link.ts
packages/alfa-selector/src/selector/simple/pseudo-class/visited.ts
packages/alfa-selector/test/pseudo-class.spec.tsx
packages/alfa-selector/tsconfig.json

Support `:any-link`

---

packages/alfa-dom/src/native.ts
packages/alfa-dom/test/native.spec.tsx

Grab adopted stylesheets in Native.fromNode

---

.changeset/soft-dodos-carry.md
.github/workflows/alfa-release.yml

Revert to yarn publish

---

.changeset/strange-masks-fly.md
docs/review/api/alfa-selector.api.md
packages/alfa-selector/src/selector/simple/pseudo-class/checked.ts
packages/alfa-selector/src/selector/simple/pseudo-class/index.ts
packages/alfa-selector/src/tsconfig.json
packages/alfa-selector/test/pseudo-class.spec.tsx

Resolves https://siteimprove.slack.com/archives/C0AL4K656/p1727104365760179

Support `:checked` pseudo-class

---

.changeset/stale-feet-lick.md
packages/alfa-dom/src/node.ts
packages/alfa-web/package.json
packages/alfa-web/src/page.ts
packages/alfa-web/src/tsconfig.json
yarn.lock

Cache some deserialisations

---

.changeset/fast-students-count.md
docs/review/api/alfa-dom.api.md
packages/alfa-dom/src/node.ts
packages/alfa-dom/test/node.spec.tsx

Include path in Low verbosity Node serialization

---

.changeset/hot-comics-unite.md
packages/alfa-aria/src/feature.ts

Add support for the `<search>` element

---

.changeset/three-cherries-fry.md
docs/review/api/alfa-act.api.md
packages/alfa-act/src/outcome.ts
packages/alfa-act/src/rule.ts

Add minimal serialization of rules
